var searchData=
[
  ['opannotarget_3134',['OpAnnoTarget',['../structcirct_1_1firrtl_1_1OpAnnoTarget.html',1,'circt::firrtl']]],
  ['opconversionpattern_3135',['OpConversionPattern',['../classmlir_1_1OpConversionPattern.html',1,'mlir::OpConversionPattern&lt; SourceOp &gt;'],['../classOpConversionPattern.html',1,'OpConversionPattern']]],
  ['opconversionpattern_3c_20affineloadop_20_3e_3136',['OpConversionPattern&lt; AffineLoadOp &gt;',['../classmlir_1_1OpConversionPattern.html',1,'mlir']]],
  ['opconversionpattern_3c_20affinestoreop_20_3e_3137',['OpConversionPattern&lt; AffineStoreOp &gt;',['../classmlir_1_1OpConversionPattern.html',1,'mlir']]],
  ['opconversionpattern_3c_20handshake_3a_3afuncop_20_3e_3138',['OpConversionPattern&lt; handshake::FuncOp &gt;',['../classmlir_1_1OpConversionPattern.html',1,'mlir']]],
  ['opconversionpattern_3c_20ifop_20_3e_3139',['OpConversionPattern&lt; IfOp &gt;',['../classmlir_1_1OpConversionPattern.html',1,'mlir']]],
  ['operationpass_3140',['OperationPass',['../classmlir_1_1OperationPass.html',1,'mlir']]],
  ['opfileinfo_3141',['OpFileInfo',['../structcirct_1_1ExportVerilog_1_1OpFileInfo.html',1,'circt::ExportVerilog']]],
  ['opoperand_3142',['OpOperand',['../classcirct_1_1support_1_1OpOperand.html',1,'circt::support']]],
  ['oprewritepattern_3143',['OpRewritePattern',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20calyx_3a_3aassignop_20_3e_3144',['OpRewritePattern&lt; calyx::AssignOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20calyx_3a_3acombgroupop_20_3e_3145',['OpRewritePattern&lt; calyx::CombGroupOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20calyx_3a_3agroupdoneop_20_3e_3146',['OpRewritePattern&lt; calyx::GroupDoneOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20calyx_3a_3agroupop_20_3e_3147',['OpRewritePattern&lt; calyx::GroupOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20ctrlop_20_3e_3148',['OpRewritePattern&lt; CtrlOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20ifop_20_3e_3149',['OpRewritePattern&lt; IfOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20mlir_3a_3afuncop_20_3e_3150',['OpRewritePattern&lt; mlir::FuncOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20mlir_3a_3amoduleop_20_3e_3151',['OpRewritePattern&lt; mlir::ModuleOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20optype_20_3e_3152',['OpRewritePattern&lt; OpType &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20scf_3a_3aexecuteregionop_20_3e_3153',['OpRewritePattern&lt; scf::ExecuteRegionOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['orop_3154',['OrOp',['../class__comb__ops__ext_1_1OrOp.html',1,'_comb_ops_ext']]],
  ['owningopref_3155',['OwningOpRef',['../classmlir_1_1OwningOpRef.html',1,'mlir']]]
];
