CIRCT: circt::BuildControl Class Reference
circt::BuildControl Class Reference
Builds a control schedule by traversing the CFG of the function and associating this with the previously created groups.
Private Member Functions
LogicalResult PartiallyLowerFuncToComp (mlir::FuncOp funcOp, PatternRewriter &rewriter) const override
Partial lowering implementation.
LogicalResult scheduleBasicBlock (PatternRewriter &rewriter, const DenseSet< Block * > &path, mlir::Block *parentCtrlBlock, mlir::Block *block) const
Sequentially schedules the groups that registered themselves with 'block'.
LogicalResult schedulePath (PatternRewriter &rewriter, const DenseSet< Block * > &path, Location loc, Block *from, Block *to, Block *parentCtrlBlock) const
Schedules a block by inserting a branch argument assignment block (if any) before recursing into the scheduling of the block innards.
LogicalResult buildCFGControl (DenseSet< Block * > path, PatternRewriter &rewriter, mlir::Block *parentCtrlBlock, mlir::Block *preBlock, mlir::Block *block) const
calyx::WhileOp buildWhileCtrlOp (WhileOpInterface whileOp, SmallVector< calyx::GroupOp > initGroups, Location loc, PatternRewriter &rewriter) const
FuncOpPartialLoweringPattern (MLIRContext *context, LogicalResult &resRef, FuncMapping &_funcMap, ProgramLoweringState &pls)
Additional Inherited Members
Public Member Functions inherited from circt::FuncOpPartialLoweringPattern
FuncOpPartialLoweringPattern (MLIRContext *context, LogicalResult &resRef, FuncMapping &_funcMap, ProgramLoweringState &pls)
LogicalResult partiallyLower (mlir::FuncOp funcOp, PatternRewriter &rewriter) const override final
calyx::ComponentOp * getComponent () const
ComponentLoweringState & getComponentState () const
ProgramLoweringState & progState () const
Public Member Functions inherited from circt::PartialLoweringPattern< mlir::FuncOp >
PartialLoweringPattern (MLIRContext *ctx, LogicalResult &resRef)
LogicalResult matchAndRewrite (mlir::FuncOp op, PatternRewriter &rewriter) const override
Protected Attributes inherited from circt::FuncOpPartialLoweringPattern
FuncMapping & funcMap
Detailed Description
Builds a control schedule by traversing the CFG of the function and associating this with the previously created groups.
For simplicity, the generated control flow is expanded for all possible paths in the input DAG. This elaborated control flow is later reduced in the runControlFlowSimplification passes.
Definition at line 2018 of file SCFToCalyx.cpp.
Member Function Documentation
buildCFGControl()
LogicalResult circt::BuildControl::buildCFGControl (DenseSet< Block * > path, PatternRewriter & rewriter, mlir::Block * parentCtrlBlock, mlir::Block * preBlock, mlir::Block * block) const inline private
TODO(mortbopet): we could choose to support ie. std.switch, but it would probably be easier to just require it to be lowered beforehand.
Wrap each branch inside an if/else.
Schedule sequentially within the current parent control block.
Definition at line 2130 of file SCFToCalyx.cpp.
References circt::calyx::direction::get().
buildWhileCtrlOp()
calyx::WhileOp circt::BuildControl::buildWhileCtrlOp (WhileOpInterface whileOp, SmallVector< calyx::GroupOp > initGroups, Location loc, PatternRewriter & rewriter) const inline private
Insert while iter arg initialization group(s). Emit a parallel group to assign one or more registers all at once.
Insert the while op itself.
If a bound was specified, add it.
Definition at line 2194 of file SCFToCalyx.cpp.
References circt::calyx::direction::get(), circt::WhileOpInterface::getBound(), circt::WhileOpInterface::getConditionValue(), and circt::WhileOpInterface::getOperation().
FuncOpPartialLoweringPattern()
circt::FuncOpPartialLoweringPattern::FuncOpPartialLoweringPattern inline private
Definition at line 743 of file SCFToCalyx.cpp.
PartiallyLowerFuncToComp()
LogicalResult circt::BuildControl::PartiallyLowerFuncToComp (mlir::FuncOp funcOp, PatternRewriter & rewriter) const inline override private virtual
Partial lowering implementation.
Implements circt::FuncOpPartialLoweringPattern.
Definition at line 2022 of file SCFToCalyx.cpp.
scheduleBasicBlock()
LogicalResult circt::BuildControl::scheduleBasicBlock (PatternRewriter & rewriter, const DenseSet< Block * > & path, mlir::Block * parentCtrlBlock, mlir::Block * block) const inline private
Sequentially schedules the groups that registered themselves with 'block'.
Only schedule the 'after' block. The 'before' block is implicitly scheduled when evaluating the while condition.
Schedule pipeline stages in the parallel group directly.
Definition at line 2035 of file SCFToCalyx.cpp.
schedulePath()
LogicalResult circt::BuildControl::schedulePath (PatternRewriter & rewriter, const DenseSet< Block * > & path, Location loc, Block * from, Block * to, Block * parentCtrlBlock) const inline private
Schedules a block by inserting a branch argument assignment block (if any) before recursing into the scheduling of the block innards.
Blocks 'from' and 'to' refer to blocks in the source program. parentCtrlBlock refers to the control block wherein control operations are to be inserted.
Schedule any registered block arguments to be executed before the body of the branch.
Definition at line 2115 of file SCFToCalyx.cpp.
The documentation for this class was generated from the following file:
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp