CIRCT: circt::firrtl::InstanceGraphNode Class Reference
circt::firrtl::InstanceGraphNode Class Reference
This is a Node in the InstanceGraph.
#include <InstanceGraph.h>
Classes
struct UseIterator
Iterator for module uses.
Public Types
using iterator = detail::AddressIterator< InstanceList::iterator >
Iterate the instance records in this module.
Public Member Functions
Operation * getModule () const
Get the module that this node is tracking.
iterator begin ()
iterator end ()
bool noUses ()
Return true if there are no more instances of this module.
bool hasOneUse ()
Return true if this module has exactly one use.
size_t getNumUses ()
Get the number of direct instantiations of this module.
UseIterator usesBegin ()
Iterate the instance records which instantiate this module.
UseIterator usesEnd ()
llvm::iterator_range< UseIterator > uses ()
InstanceRecord * addInstance (InstanceOp instance, InstanceGraphNode *target)
Record a new instance op in the body of this module.
Private Types
using InstanceList = llvm::iplist< InstanceRecord >
Private Member Functions
InstanceGraphNode ()
InstanceGraphNode (const InstanceGraphNode &)=delete
void recordUse (InstanceRecord *record)
Record that a module instantiates this module.
Private Attributes
Operation * module
The module.
InstanceList instances
List of instance operations in this module.
InstanceRecord * firstUse = nullptr
List of instances which instantiate this module.
Friends
class InstanceRecord
class InstanceGraph
Iterates over the handshake::FuncOp's in the program to build an instance graph.
Detailed Description
This is a Node in the InstanceGraph.
Each node represents a Module in a Circuit. Both external modules and regular modules can be represented by this class. It is possible to efficiently iterate all modules instantiated by this module, as well as all instantiations of this module.
Definition at line 86 of file InstanceGraph.h.
Member Typedef Documentation
InstanceList
using circt::firrtl::InstanceGraphNode::InstanceList = llvm::iplist<InstanceRecord> private
Definition at line 87 of file InstanceGraph.h.
iterator
using circt::firrtl::InstanceGraphNode::iterator = detail::AddressIterator<InstanceList::iterator>
Iterate the instance records in this module.
Definition at line 94 of file InstanceGraph.h.
Constructor & Destructor Documentation
InstanceGraphNode() [1/2]
circt::firrtl::InstanceGraphNode::InstanceGraphNode () inline private
Definition at line 143 of file InstanceGraph.h.
InstanceGraphNode() [2/2]
circt::firrtl::InstanceGraphNode::InstanceGraphNode (const InstanceGraphNode &) private delete
Member Function Documentation
addInstance()
InstanceRecord * InstanceGraphNode::addInstance (InstanceOp instance, InstanceGraphNode * target)
Record a new instance op in the body of this module.
Returns a newly allocated InstanceRecord which will be owned by this node.
Definition at line 27 of file InstanceGraph.cpp.
References InstanceRecord, instances, and recordUse().
begin()
iterator circt::firrtl::InstanceGraphNode::begin () inline
Definition at line 95 of file InstanceGraph.h.
References instances.
Referenced by llvm::GraphTraits< circt::firrtl::InstanceGraphNode * >::child_begin().
end()
iterator circt::firrtl::InstanceGraphNode::end () inline
Definition at line 96 of file InstanceGraph.h.
References instances.
Referenced by llvm::GraphTraits< circt::firrtl::InstanceGraphNode * >::child_end().
getModule()
Operation* circt::firrtl::InstanceGraphNode::getModule () const inline
Get the module that this node is tracking.
Definition at line 91 of file InstanceGraph.h.
References module.
Referenced by circt::firrtl::InstanceGraph::erase(), circt::firrtl::InstancePathCache::getAbsolutePaths(), circt::firrtl::InstanceGraph::getReferencedModule(), and circt::firrtl::InstanceGraph::getTopLevelModule().
getNumUses()
size_t circt::firrtl::InstanceGraphNode::getNumUses () inline
Get the number of direct instantiations of this module.
Definition at line 105 of file InstanceGraph.h.
References usesBegin(), and usesEnd().
hasOneUse()
bool circt::firrtl::InstanceGraphNode::hasOneUse () inline
Return true if this module has exactly one use.
Definition at line 102 of file InstanceGraph.h.
References uses().
noUses()
bool circt::firrtl::InstanceGraphNode::noUses () inline
Return true if there are no more instances of this module.
Definition at line 99 of file InstanceGraph.h.
References firstUse.
Referenced by circt::firrtl::InstanceGraph::erase().
recordUse()
void InstanceGraphNode::recordUse (InstanceRecord * record) private
Record that a module instantiates this module.
Definition at line 35 of file InstanceGraph.cpp.
References firstUse, circt::firrtl::InstanceRecord::nextUse, and circt::firrtl::InstanceRecord::prevUse.
Referenced by addInstance().
uses()
llvm::iterator_range<UseIterator> circt::firrtl::InstanceGraphNode::uses () inline
Definition at line 132 of file InstanceGraph.h.
References usesBegin(), and usesEnd().
Referenced by hasOneUse().
usesBegin()
UseIterator circt::firrtl::InstanceGraphNode::usesBegin () inline
Iterate the instance records which instantiate this module.
Definition at line 130 of file InstanceGraph.h.
Referenced by llvm::GraphTraits< Inverse< circt::firrtl::InstanceGraphNode * > >::child_begin(), getNumUses(), and uses().
usesEnd()
UseIterator circt::firrtl::InstanceGraphNode::usesEnd () inline
Definition at line 131 of file InstanceGraph.h.
Referenced by llvm::GraphTraits< Inverse< circt::firrtl::InstanceGraphNode * > >::child_end(), getNumUses(), and uses().
Friends And Related Function Documentation
InstanceGraph
friend class InstanceGraph friend
Iterates over the handshake::FuncOp's in the program to build an instance graph.
In doing so, we detect whether there are any cycles in this graph, as well as infer a top function for the design by performing a topological sort of the instance graph. The result of this sort is placed in sortedFuncs.
Definition at line 161 of file InstanceGraph.h.
InstanceRecord
friend class InstanceRecord friend
Definition at line 141 of file InstanceGraph.h.
Referenced by addInstance().
Member Data Documentation
firstUse
InstanceRecord* circt::firrtl::InstanceGraphNode::firstUse = nullptr private
List of instances which instantiate this module.
Definition at line 158 of file InstanceGraph.h.
Referenced by circt::firrtl::InstanceRecord::erase(), noUses(), and recordUse().
instances
InstanceList circt::firrtl::InstanceGraphNode::instances private
List of instance operations in this module.
This member owns the InstanceRecords, which may be pointed to by other InstanceGraohNode's use lists.
Definition at line 155 of file InstanceGraph.h.
Referenced by addInstance(), begin(), end(), and circt::firrtl::InstanceRecord::erase().
module
Operation* circt::firrtl::InstanceGraphNode::module private
The module.
Definition at line 150 of file InstanceGraph.h.
Referenced by _msft_ops_ext.InstanceBuilder::create_default_value(), _hw_ops_ext.InstanceBuilder::create_default_value(), getModule(), _msft_ops_ext.InstanceBuilder::operand_names(), _hw_ops_ext.InstanceBuilder::operand_names(), _msft_ops_ext.InstanceBuilder::result_names(), and _hw_ops_ext.InstanceBuilder::result_names().
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/InstanceGraph.h
lib/Dialect/FIRRTL/InstanceGraph.cpp