CIRCT: circt::hw::SymbolCache Class Reference
circt::hw::SymbolCache Class Reference
This stores lookup tables to make manipulating and working with the IR more efficient.
#include <HWSymCache.h>
Classes
class Item
Public Member Functions
void addDefinition (mlir::StringAttr symbol, mlir::Operation *op)
In the building phase, add symbols.
void addDefinition (mlir::StringAttr modSymbol, mlir::StringAttr name, mlir::Operation *op, size_t port=~0ULL)
void addDefinition (InnerRefAttr name, mlir::Operation *op, size_t port=~0ULL)
void freeze ()
Mark the cache as frozen, which allows it to be shared across threads.
mlir::Operation * getDefinition (mlir::StringAttr symbol) const
mlir::Operation * getDefinition (mlir::FlatSymbolRefAttr symbol) const
Item getDefinition (mlir::StringAttr modSymbol, mlir::StringAttr name) const
Item getDefinition (InnerRefAttr name) const
Private Member Functions
Item lookup (InnerRefAttr attr) const
mlir::Operation * lookup (mlir::StringAttr attr) const
Private Attributes
bool isFrozen = false
llvm::DenseMap< mlir::Attribute, Item > symbolCache
This stores a lookup table from symbol attribute to the operation (hw.module, hw.instance, etc) that defines it.
Detailed Description
This stores lookup tables to make manipulating and working with the IR more efficient.
There are two phases to this object: the "building" phase in which it is "write only" and then the "using" phase which is read-only (and thus can be used by multiple threads). The "freeze" method transitions between the two states.
Definition at line 26 of file HWSymCache.h.
Member Function Documentation
addDefinition() [1/3]
void circt::hw::SymbolCache::addDefinition (InnerRefAttr name, mlir::Operation * op, size_t port = ~0ULL) inline
Definition at line 56 of file HWSymCache.h.
References isFrozen, and symbolCache.
addDefinition() [2/3]
void circt::hw::SymbolCache::addDefinition (mlir::StringAttr modSymbol, mlir::StringAttr name, mlir::Operation * op, size_t port = ~0ULL) inline
Definition at line 48 of file HWSymCache.h.
References circt::calyx::direction::get(), isFrozen, and symbolCache.
addDefinition() [3/3]
void circt::hw::SymbolCache::addDefinition (mlir::StringAttr symbol, mlir::Operation * op) inline
In the building phase, add symbols.
Definition at line 42 of file HWSymCache.h.
References isFrozen, and symbolCache.
Referenced by circt::msft::TclEmitter::populate().
freeze()
void circt::hw::SymbolCache::freeze () inline
Mark the cache as frozen, which allows it to be shared across threads.
Definition at line 63 of file HWSymCache.h.
References isFrozen.
Referenced by circt::msft::TclEmitter::populate().
getDefinition() [1/4]
Item circt::hw::SymbolCache::getDefinition (InnerRefAttr name) const inline
Definition at line 77 of file HWSymCache.h.
References lookup().
getDefinition() [2/4]
mlir::Operation* circt::hw::SymbolCache::getDefinition (mlir::FlatSymbolRefAttr symbol) const inline
Definition at line 69 of file HWSymCache.h.
References lookup().
getDefinition() [3/4]
Item circt::hw::SymbolCache::getDefinition (mlir::StringAttr modSymbol, mlir::StringAttr name) const inline
Definition at line 73 of file HWSymCache.h.
References circt::calyx::direction::get(), and lookup().
getDefinition() [4/4]
mlir::Operation* circt::hw::SymbolCache::getDefinition (mlir::StringAttr symbol) const inline
Definition at line 65 of file HWSymCache.h.
References lookup().
Referenced by circt::msft::TclEmitter::getDefinition(), and circt::msft::TclEmitter::populate().
lookup() [1/2]
Item circt::hw::SymbolCache::lookup (InnerRefAttr attr) const inline private
Definition at line 80 of file HWSymCache.h.
References isFrozen, and symbolCache.
Referenced by getDefinition().
lookup() [2/2]
mlir::Operation* circt::hw::SymbolCache::lookup (mlir::StringAttr attr) const inline private
Definition at line 86 of file HWSymCache.h.
References isFrozen, and symbolCache.
Member Data Documentation
isFrozen
bool circt::hw::SymbolCache::isFrozen = false private
Definition at line 95 of file HWSymCache.h.
Referenced by addDefinition(), freeze(), and lookup().
symbolCache
llvm::DenseMap<mlir::Attribute, Item> circt::hw::SymbolCache::symbolCache private
This stores a lookup table from symbol attribute to the operation (hw.module, hw.instance, etc) that defines it.
TODO: It is super annoying that symbols are defined as StringAttr, but are then referenced as FlatSymbolRefAttr. Why can't we have nice pointer uniqued things?? :-(
Definition at line 102 of file HWSymCache.h.
Referenced by addDefinition(), and lookup().
The documentation for this class was generated from the following file:
include/circt/Dialect/HW/HWSymCache.h