CIRCT: circt::ComponentLoweringState Class Reference
circt::ComponentLoweringState Class Reference
Public Member Functions
ComponentLoweringState (ProgramLoweringState &pls, calyx::ComponentOp compOp)
ProgramLoweringState & getProgramState ()
calyx::ComponentOp getComponentOp ()
Returns the calyx::ComponentOp associated with this lowering state.
std::string getUniqueName (StringRef prefix)
Returns a unique name within compOp with the provided prefix.
StringRef getUniqueName (Operation *op)
Returns a unique name associated with a specific operation.
void setUniqueName (Operation *op, StringRef prefix)
Registers a unique name for a given operation using a provided prefix.
template<typename TLibraryOp >
TLibraryOp getNewLibraryOpInstance (PatternRewriter &rewriter, Location loc, TypeRange resTypes)
void registerEvaluatingGroup (Value v, calyx::GroupInterface group)
Register value v as being evaluated when scheduling group.
template<typename TGroupOp = calyx::GroupInterface>
TGroupOp getEvaluatingGroup (Value v)
Return the group which evaluates the value v.
void addReturnReg (calyx::RegisterOp reg, unsigned idx)
Register reg as being the idx'th return value register.
calyx::RegisterOp getReturnReg (unsigned idx)
Returns the idx'th return value register.
Value getConstant (PatternRewriter &rewriter, Location loc, int64_t value, unsigned width)
Returns an SSA value for an arbitrary precision constant defined within compOp.
void addBlockScheduleable (mlir::Block *block, const Scheduleable &scheduleable)
Register 'scheduleable' as being generated through lowering 'block'.
SmallVector< Scheduleable > getBlockScheduleables (mlir::Block *block)
Returns an ordered list of schedulables which registered themselves to be a result of lowering the block in the source program.
void addBlockArgGroup (Block *from, Block *to, calyx::GroupOp grp)
Register 'grp' as a group which performs block argument register transfer when transitioning from basic block from to to.
ArrayRef< calyx::GroupOp > getBlockArgGroups (Block *from, Block *to)
Returns a list of groups to be evaluated to perform the block argument register assignments when transitioning from basic block 'from' to 'to'.
void addBlockArgReg (Block *block, calyx::RegisterOp reg, unsigned idx)
Register reg as being the idx'th argument register for block.
const DenseMap< unsigned, calyx::RegisterOp > & getBlockArgRegs (Block *block)
Return a mapping of block argument indices to block argument registers.
void addPipelineReg (Operation *stage, calyx::RegisterOp reg, unsigned idx)
Register reg as being the idx'th pipeline register for the stage.
const DenseMap< unsigned, calyx::RegisterOp > & getPipelineRegs (Operation *stage)
Return a mapping of stage result indices to pipeline registers.
void addPipelinePrologue (Operation *op, SmallVector< StringAttr > groupNames)
Add a stage's groups to the pipeline prologue.
void addPipelineEpilogue (Operation *op, SmallVector< StringAttr > groupNames)
Add a stage's groups to the pipeline epilogue.
SmallVector< SmallVector< StringAttr > > getPipelineProlouge (Operation *op)
Get the pipeline prologue.
SmallVector< SmallVector< StringAttr > > getPipelineEpilouge (Operation *op)
Get the pipeline epilogue.
void createPipelinePrologue (Operation *op, PatternRewriter &rewriter)
Create the pipeline prologue.
void createPipelineEpilogue (Operation *op, PatternRewriter &rewriter)
Create the pipeline epilogue.
void addWhileIterReg (WhileOpInterface whileOp, calyx::RegisterOp reg, unsigned idx)
Register reg as being the idx'th iter_args register for 'whileOp'.
calyx::RegisterOp getWhileIterReg (WhileOpInterface whileOp, unsigned idx)
Return a mapping of block argument indices to block argument registers.
const DenseMap< unsigned, calyx::RegisterOp > & getWhileIterRegs (WhileOpInterface whileOp)
Return a mapping of block argument indices to block argument registers.
void setWhileLatchGroup (WhileOpInterface whileOp, calyx::GroupOp grp)
Registers grp to be the while latch group of whileOp.
calyx::GroupOp getWhileLatchGroup (WhileOpInterface whileOp)
Retrieve the while latch group registered for whileOp.
void registerMemoryInterface (Value memref, const CalyxMemoryInterface &memoryInterface)
Registers a memory interface as being associated with a memory identified by 'memref'.
CalyxMemoryInterface getMemoryInterface (Value memref)
Returns the memory interface registered for the given memref.
Optional< CalyxMemoryInterface > isInputPortOfMemory (Value v)
If v is an input to any memory registered within this component, returns the memory.
void setFuncOpResultMapping (const DenseMap< unsigned, unsigned > &mapping)
Assign a mapping between the source funcOp result indices and the corresponding output port indices of this componentOp.
unsigned getFuncOpResultMapping (unsigned funcReturnIdx)
Get the output port index of this component for which the funcReturnIdx of the original function maps to.
Private Attributes
ProgramLoweringState & programLoweringState
A reference to the parent program lowering state.
calyx::ComponentOp compOp
The component which this lowering state is associated to.
std::map< std::string, unsigned > prefixIdMap
A mapping of string prefixes and the current uniqueness counter for that prefix.
std::map< Operation *, std::string > opNames
A mapping from Operations and previously assigned unique name of the op.
DenseMap< Value, calyx::GroupInterface > valueGroupAssigns
A mapping between SSA values and the groups which assign them.
DenseMap< unsigned, calyx::RegisterOp > returnRegs
A mapping from return value indexes to return value registers.
DenseMap< APInt, Value > constants
A mapping of currently available constants in this component.
DenseMap< mlir::Block *, SmallVector< Scheduleable > > blockScheduleables
BlockScheduleables is a list of scheduleables that should be sequentially executed when executing the associated basic block.
DenseMap< Block *, DenseMap< unsigned, calyx::RegisterOp > > blockArgRegs
A mapping from blocks to block argument registers.
DenseMap< Operation *, DenseMap< unsigned, calyx::RegisterOp > > pipelineRegs
A mapping from pipeline stages to their registers.
DenseMap< Operation *, SmallVector< SmallVector< StringAttr > > > pipelinePrologue
A mapping from pipeline ops to a vector of vectors of group names that constitute the pipeline prologue.
DenseMap< Operation *, SmallVector< SmallVector< StringAttr > > > pipelineEpilogue
A mapping from pipeline ops to a vector of vectors of group names that constitute the pipeline epilogue.
DenseMap< Block *, DenseMap< Block *, SmallVector< calyx::GroupOp > > > blockArgGroups
Block arg groups is a list of groups that should be sequentially executed when passing control from the source to destination block.
DenseMap< Operation *, calyx::GroupOp > whileLatchGroups
A while latch group is a group that should be sequentially executed when finishing a while loop body.
DenseMap< Operation *, DenseMap< unsigned, calyx::RegisterOp > > whileIterRegs
A mapping from while ops to iteration argument registers.
DenseMap< Value, CalyxMemoryInterface > memories
A mapping from memref's to their corresponding Calyx memory interface.
DenseMap< unsigned, unsigned > funcOpResultMapping
A mapping between the source funcOp result indices and the corresponding output port indices of this componentOp.
Detailed Description
Definition at line 248 of file SCFToCalyx.cpp.
Constructor & Destructor Documentation
ComponentLoweringState()
circt::ComponentLoweringState::ComponentLoweringState (ProgramLoweringState & pls, calyx::ComponentOp compOp) inline
Definition at line 250 of file SCFToCalyx.cpp.
Member Function Documentation
addBlockArgGroup()
void circt::ComponentLoweringState::addBlockArgGroup (Block * from, Block * to, calyx::GroupOp grp) inline
Register 'grp' as a group which performs block argument register transfer when transitioning from basic block from to to.
Definition at line 364 of file SCFToCalyx.cpp.
addBlockArgReg()
void circt::ComponentLoweringState::addBlockArgReg (Block * block, calyx::RegisterOp reg, unsigned idx) inline
Register reg as being the idx'th argument register for block.
Definition at line 375 of file SCFToCalyx.cpp.
References seq::reg(), and size().
addBlockScheduleable()
void circt::ComponentLoweringState::addBlockScheduleable (mlir::Block * block, const Scheduleable & scheduleable) inline
Register 'scheduleable' as being generated through lowering 'block'.
TODO(mortbopet): Add a post-insertion check to ensure that the use-def ordering invariant holds for the groups. When the control schedule is generated, scheduleables within a block are emitted sequentially based on the order that this function was called during conversion.
Currently, we assume this to always be true. Walking the FuncOp IR implies sequential iteration over operations within basic blocks.
Definition at line 345 of file SCFToCalyx.cpp.
addPipelineEpilogue()
void circt::ComponentLoweringState::addPipelineEpilogue (Operation * op, SmallVector< StringAttr > groupNames) inline
Add a stage's groups to the pipeline epilogue.
Definition at line 405 of file SCFToCalyx.cpp.
addPipelinePrologue()
void circt::ComponentLoweringState::addPipelinePrologue (Operation * op, SmallVector< StringAttr > groupNames) inline
Add a stage's groups to the pipeline prologue.
Definition at line 400 of file SCFToCalyx.cpp.
addPipelineReg()
void circt::ComponentLoweringState::addPipelineReg (Operation * stage, calyx::RegisterOp reg, unsigned idx) inline
Register reg as being the idx'th pipeline register for the stage.
Definition at line 387 of file SCFToCalyx.cpp.
References seq::reg().
addReturnReg()
void circt::ComponentLoweringState::addReturnReg (calyx::RegisterOp reg, unsigned idx) inline
Register reg as being the idx'th return value register.
Definition at line 310 of file SCFToCalyx.cpp.
References seq::reg().
addWhileIterReg()
void circt::ComponentLoweringState::addWhileIterReg (WhileOpInterface whileOp, calyx::RegisterOp reg, unsigned idx) inline
Register reg as being the idx'th iter_args register for 'whileOp'.
Definition at line 446 of file SCFToCalyx.cpp.
References circt::WhileOpInterface::getBodyArgs(), circt::WhileOpInterface::getOperation(), and seq::reg().
createPipelineEpilogue()
void circt::ComponentLoweringState::createPipelineEpilogue (Operation * op, PatternRewriter & rewriter) inline
Create the pipeline epilogue.
Definition at line 433 of file SCFToCalyx.cpp.
createPipelinePrologue()
void circt::ComponentLoweringState::createPipelinePrologue (Operation * op, PatternRewriter & rewriter) inline
Create the pipeline prologue.
Definition at line 420 of file SCFToCalyx.cpp.
getBlockArgGroups()
ArrayRef<calyx::GroupOp> circt::ComponentLoweringState::getBlockArgGroups (Block * from, Block * to) inline
Returns a list of groups to be evaluated to perform the block argument register assignments when transitioning from basic block 'from' to 'to'.
Definition at line 370 of file SCFToCalyx.cpp.
getBlockArgRegs()
const DenseMap<unsigned, calyx::RegisterOp>& circt::ComponentLoweringState::getBlockArgRegs (Block * block) inline
Return a mapping of block argument indices to block argument registers.
Definition at line 382 of file SCFToCalyx.cpp.
getBlockScheduleables()
SmallVector<Scheduleable> circt::ComponentLoweringState::getBlockScheduleables (mlir::Block * block) inline
Returns an ordered list of schedulables which registered themselves to be a result of lowering the block in the source program.
The list order follows def-use chains between the scheduleables in the block.
In cases of a block resulting in purely combinational logic, no scheduleables registered themselves with the block.
Definition at line 353 of file SCFToCalyx.cpp.
getComponentOp()
calyx::ComponentOp circt::ComponentLoweringState::getComponentOp () inline
Returns the calyx::ComponentOp associated with this lowering state.
Definition at line 256 of file SCFToCalyx.cpp.
Referenced by circt::buildAllocOp(), circt::buildWhileIterArgAssignments(), and circt::createReg().
getConstant()
Value circt::ComponentLoweringState::getConstant (PatternRewriter & rewriter, Location loc, int64_t value, unsigned width) inline
Returns an SSA value for an arbitrary precision constant defined within compOp.
A new constant is created if no constant is found.
Definition at line 324 of file SCFToCalyx.cpp.
Referenced by circt::buildAssignmentsForRegisterWrite().
getEvaluatingGroup()
template<typename TGroupOp = calyx::GroupInterface> TGroupOp circt::ComponentLoweringState::getEvaluatingGroup (Value v) inline
Return the group which evaluates the value v.
Optionally, caller may specify the expected type of the group.
Definition at line 297 of file SCFToCalyx.cpp.
Referenced by circt::InlineCombGroups::recurseInlineCombGroups().
getFuncOpResultMapping()
unsigned circt::ComponentLoweringState::getFuncOpResultMapping (unsigned funcReturnIdx) inline
Get the output port index of this component for which the funcReturnIdx of the original function maps to.
Definition at line 523 of file SCFToCalyx.cpp.
getMemoryInterface()
CalyxMemoryInterface circt::ComponentLoweringState::getMemoryInterface (Value memref) inline
Returns the memory interface registered for the given memref.
Definition at line 496 of file SCFToCalyx.cpp.
getNewLibraryOpInstance()
template<typename TLibraryOp > TLibraryOp circt::ComponentLoweringState::getNewLibraryOpInstance (PatternRewriter & rewriter, Location loc, TypeRange resTypes) inline
Definition at line 281 of file SCFToCalyx.cpp.
getPipelineEpilouge()
SmallVector<SmallVector<StringAttr> > circt::ComponentLoweringState::getPipelineEpilouge (Operation * op) inline
Get the pipeline epilogue.
Definition at line 415 of file SCFToCalyx.cpp.
getPipelineProlouge()
SmallVector<SmallVector<StringAttr> > circt::ComponentLoweringState::getPipelineProlouge (Operation * op) inline
Get the pipeline prologue.
Definition at line 410 of file SCFToCalyx.cpp.
getPipelineRegs()
const DenseMap<unsigned, calyx::RegisterOp>& circt::ComponentLoweringState::getPipelineRegs (Operation * stage) inline
Return a mapping of stage result indices to pipeline registers.
Definition at line 395 of file SCFToCalyx.cpp.
getProgramState()
ProgramLoweringState& circt::ComponentLoweringState::getProgramState () inline
Definition at line 253 of file SCFToCalyx.cpp.
getReturnReg()
calyx::RegisterOp circt::ComponentLoweringState::getReturnReg (unsigned idx) inline
Returns the idx'th return value register.
Definition at line 317 of file SCFToCalyx.cpp.
getUniqueName() [1/2]
StringRef circt::ComponentLoweringState::getUniqueName (Operation * op) inline
Returns a unique name associated with a specific operation.
Definition at line 267 of file SCFToCalyx.cpp.
getUniqueName() [2/2]
std::string circt::ComponentLoweringState::getUniqueName (StringRef prefix) inline
Returns a unique name within compOp with the provided prefix.
Definition at line 259 of file SCFToCalyx.cpp.
Referenced by circt::buildAllocOp().
getWhileIterReg()
calyx::RegisterOp circt::ComponentLoweringState::getWhileIterReg (WhileOpInterface whileOp, unsigned idx) inline
Return a mapping of block argument indices to block argument registers.
Definition at line 456 of file SCFToCalyx.cpp.
Referenced by circt::buildWhileIterArgAssignments().
getWhileIterRegs()
const DenseMap<unsigned, calyx::RegisterOp>& circt::ComponentLoweringState::getWhileIterRegs (WhileOpInterface whileOp) inline
Return a mapping of block argument indices to block argument registers.
Definition at line 466 of file SCFToCalyx.cpp.
References circt::WhileOpInterface::getOperation().
getWhileLatchGroup()
calyx::GroupOp circt::ComponentLoweringState::getWhileLatchGroup (WhileOpInterface whileOp) inline
Retrieve the while latch group registered for whileOp.
Definition at line 478 of file SCFToCalyx.cpp.
References circt::WhileOpInterface::getOperation().
isInputPortOfMemory()
Optional<CalyxMemoryInterface> circt::ComponentLoweringState::isInputPortOfMemory (Value v) inline
If v is an input to any memory registered within this component, returns the memory.
If not, returns null.
Definition at line 505 of file SCFToCalyx.cpp.
registerEvaluatingGroup()
void circt::ComponentLoweringState::registerEvaluatingGroup (Value v, calyx::GroupInterface group) inline
Register value v as being evaluated when scheduling group.
Definition at line 290 of file SCFToCalyx.cpp.
registerMemoryInterface()
void circt::ComponentLoweringState::registerMemoryInterface (Value memref, const CalyxMemoryInterface & memoryInterface) inline
Registers a memory interface as being associated with a memory identified by 'memref'.
Definition at line 487 of file SCFToCalyx.cpp.
Referenced by circt::buildAllocOp().
setFuncOpResultMapping()
void circt::ComponentLoweringState::setFuncOpResultMapping (const DenseMap< unsigned, unsigned > & mapping) inline
Assign a mapping between the source funcOp result indices and the corresponding output port indices of this componentOp.
Definition at line 517 of file SCFToCalyx.cpp.
setUniqueName()
void circt::ComponentLoweringState::setUniqueName (Operation * op, StringRef prefix) inline
Registers a unique name for a given operation using a provided prefix.
Definition at line 274 of file SCFToCalyx.cpp.
setWhileLatchGroup()
void circt::ComponentLoweringState::setWhileLatchGroup (WhileOpInterface whileOp, calyx::GroupOp grp) inline
Registers grp to be the while latch group of whileOp.
Definition at line 471 of file SCFToCalyx.cpp.
References circt::WhileOpInterface::getOperation().
Member Data Documentation
blockArgGroups
DenseMap<Block *, DenseMap<Block *, SmallVector<calyx::GroupOp> > > circt::ComponentLoweringState::blockArgGroups private
Block arg groups is a list of groups that should be sequentially executed when passing control from the source to destination block.
Block arg groups are executed before blockScheduleables (akin to a phi-node).
Definition at line 579 of file SCFToCalyx.cpp.
blockArgRegs
DenseMap<Block *, DenseMap<unsigned, calyx::RegisterOp> > circt::ComponentLoweringState::blockArgRegs private
A mapping from blocks to block argument registers.
Definition at line 559 of file SCFToCalyx.cpp.
blockScheduleables
DenseMap<mlir::Block *, SmallVector<Scheduleable> > circt::ComponentLoweringState::blockScheduleables private
BlockScheduleables is a list of scheduleables that should be sequentially executed when executing the associated basic block.
Definition at line 556 of file SCFToCalyx.cpp.
compOp
calyx::ComponentOp circt::ComponentLoweringState::compOp private
The component which this lowering state is associated to.
Definition at line 536 of file SCFToCalyx.cpp.
constants
DenseMap<APInt, Value> circt::ComponentLoweringState::constants private
A mapping of currently available constants in this component.
Definition at line 552 of file SCFToCalyx.cpp.
funcOpResultMapping
DenseMap<unsigned, unsigned> circt::ComponentLoweringState::funcOpResultMapping private
A mapping between the source funcOp result indices and the corresponding output port indices of this componentOp.
Definition at line 594 of file SCFToCalyx.cpp.
memories
DenseMap<Value, CalyxMemoryInterface> circt::ComponentLoweringState::memories private
A mapping from memref's to their corresponding Calyx memory interface.
Definition at line 590 of file SCFToCalyx.cpp.
opNames
std::map<Operation *, std::string> circt::ComponentLoweringState::opNames private
A mapping from Operations and previously assigned unique name of the op.
Definition at line 543 of file SCFToCalyx.cpp.
pipelineEpilogue
DenseMap<Operation *, SmallVector<SmallVector<StringAttr> > > circt::ComponentLoweringState::pipelineEpilogue private
A mapping from pipeline ops to a vector of vectors of group names that constitute the pipeline epilogue.
Each inner vector consists of the groups for one stage.
Definition at line 572 of file SCFToCalyx.cpp.
pipelinePrologue
DenseMap<Operation *, SmallVector<SmallVector<StringAttr> > > circt::ComponentLoweringState::pipelinePrologue private
A mapping from pipeline ops to a vector of vectors of group names that constitute the pipeline prologue.
Each inner vector consists of the groups for one stage.
Definition at line 567 of file SCFToCalyx.cpp.
pipelineRegs
DenseMap<Operation *, DenseMap<unsigned, calyx::RegisterOp> > circt::ComponentLoweringState::pipelineRegs private
A mapping from pipeline stages to their registers.
Definition at line 562 of file SCFToCalyx.cpp.
prefixIdMap
std::map<std::string, unsigned> circt::ComponentLoweringState::prefixIdMap private
A mapping of string prefixes and the current uniqueness counter for that prefix.
Used to generate unique names.
Definition at line 540 of file SCFToCalyx.cpp.
programLoweringState
ProgramLoweringState& circt::ComponentLoweringState::programLoweringState private
A reference to the parent program lowering state.
Definition at line 533 of file SCFToCalyx.cpp.
returnRegs
DenseMap<unsigned, calyx::RegisterOp> circt::ComponentLoweringState::returnRegs private
A mapping from return value indexes to return value registers.
Definition at line 549 of file SCFToCalyx.cpp.
valueGroupAssigns
DenseMap<Value, calyx::GroupInterface> circt::ComponentLoweringState::valueGroupAssigns private
A mapping between SSA values and the groups which assign them.
Definition at line 546 of file SCFToCalyx.cpp.
whileIterRegs
DenseMap<Operation *, DenseMap<unsigned, calyx::RegisterOp> > circt::ComponentLoweringState::whileIterRegs private
A mapping from while ops to iteration argument registers.
Definition at line 587 of file SCFToCalyx.cpp.
whileLatchGroups
DenseMap<Operation *, calyx::GroupOp> circt::ComponentLoweringState::whileLatchGroups private
A while latch group is a group that should be sequentially executed when finishing a while loop body.
The execution of this group will write the yield'ed loop body values to the iteration argument registers.
Definition at line 584 of file SCFToCalyx.cpp.
The documentation for this class was generated from the following file:
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp