CIRCT: LoopNetworkRewriter Class Reference
LoopNetworkRewriter Class Reference
Public Member Functions
LoopNetworkRewriter (FuncOpLowering &fol)
LogicalResult processFunction (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
Private Types
using ExitPair = std::pair< Block *, Block * >
Private Member Functions
LogicalResult processOuterLoop (Location loc, Block *loopHeader, Block *loopLatch)
BufferOp buildContinueNetwork (Block *loopHeader, Block *loopLatch, Backedge &loopPrimingInput)
void buildExitNetwork (Block *loopHeader, const std::set< ExitPair > &exitPairs, BufferOp loopPrimingRegister, Backedge &loopPrimingInput)
Private Attributes
ConversionPatternRewriter * rewriter = nullptr
std::set< Block * > visited
std::list< Block * > queue
DominanceInfo domInfo
FuncOpLowering & fol
Detailed Description
Definition at line 706 of file StandardToHandshake.cpp.
Member Typedef Documentation
ExitPair
using LoopNetworkRewriter::ExitPair = std::pair<Block *, Block *> private
Definition at line 716 of file StandardToHandshake.cpp.
Constructor & Destructor Documentation
LoopNetworkRewriter()
LoopNetworkRewriter::LoopNetworkRewriter (FuncOpLowering & fol) inline
Definition at line 708 of file StandardToHandshake.cpp.
Member Function Documentation
buildContinueNetwork()
BufferOp LoopNetworkRewriter::buildContinueNetwork (Block * loopHeader, Block * loopLatch, Backedge & loopPrimingInput) private
Definition at line 840 of file StandardToHandshake.cpp.
References getControlMerge().
buildExitNetwork()
void LoopNetworkRewriter::buildExitNetwork (Block * loopHeader, const std::set< ExitPair > & exitPairs, BufferOp loopPrimingRegister, Backedge & loopPrimingInput) private
Definition at line 948 of file StandardToHandshake.cpp.
References getControlCondBranch(), and circt::Backedge::setValue().
processFunction()
LogicalResult LoopNetworkRewriter::processFunction (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 751 of file StandardToHandshake.cpp.
References hasMultiplePredecessors(), and isReachable().
Referenced by FuncOpLowering::loopNetworkRewriting().
processOuterLoop()
LogicalResult LoopNetworkRewriter::processOuterLoop (Location loc, Block * loopHeader, Block * loopLatch) private
Definition at line 994 of file StandardToHandshake.cpp.
References blockBFS(), Continue, circt::BackedgeBuilder::get(), isReachable(), and SkipSuccessors.
Member Data Documentation
domInfo
DominanceInfo LoopNetworkRewriter::domInfo private
Definition at line 741 of file StandardToHandshake.cpp.
fol
FuncOpLowering& LoopNetworkRewriter::fol private
Definition at line 742 of file StandardToHandshake.cpp.
queue
std::list<Block *> LoopNetworkRewriter::queue private
Definition at line 740 of file StandardToHandshake.cpp.
rewriter
ConversionPatternRewriter* LoopNetworkRewriter::rewriter = nullptr private
Definition at line 738 of file StandardToHandshake.cpp.
visited
std::set<Block *> LoopNetworkRewriter::visited private
Definition at line 739 of file StandardToHandshake.cpp.
The documentation for this class was generated from the following file:
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp