CIRCT: circt::firrtl::InstanceGraph Class Reference
circt::firrtl::InstanceGraph Class Reference
This graph tracks modules and where they are instantiated.
#include <InstanceGraph.h>
Public Types
using iterator = detail::AddressIterator< NodeList::iterator >
Iterate through all modules.
Public Member Functions
InstanceGraph (Operation *operation)
Create a new module graph of a circuit.
InstanceGraphNode * getTopLevelNode ()
Get the node corresponding to the top-level module of a circuit.
FModuleLike getTopLevelModule ()
Get the module corresponding to the top-lebel module of a circuit.
InstanceGraphNode * lookup (Operation *op)
Look up an InstanceGraphNode for a module.
InstanceGraphNode * lookup (StringAttr name)
Lookup an module by name.
InstanceGraphNode * operator[] (Operation *op)
Lookup an InstanceGraphNode for a module.
Operation * getReferencedModule (InstanceOp op)
Look up the referenced module from an InstanceOp.
bool isAncestor (FModuleLike child, FModuleOp parent)
Check if child is instantiated by a parent.
iterator begin ()
iterator end ()
InstanceGraphNode * addModule (FModuleLike module)
Add a newly created module to the instance graph.
void erase (InstanceGraphNode *node)
Remove this module from the instance graph.
void replaceInstance (InstanceOp inst, InstanceOp newInst)
Replaces an instance of a module with another instance.
Static Public Member Functions
static NodeList InstanceGraph::* getSublistAccessgetSublistAccess (Operation *)
Returns pointer to member of operation list.
Private Types
using NodeList = llvm::iplist< InstanceGraphNode >
This is the list of InstanceGraphNodes in the graph.
Private Member Functions
InstanceGraph (const InstanceGraph &)=delete
InstanceGraphNode * getOrAddNode (StringAttr name)
Get the node corresponding to the module.
Private Attributes
InstanceGraphNode * topLevelNode
NodeList nodes
The storage for graph nodes, with deterministic iteration.
llvm::DenseMap< Attribute, InstanceGraphNode * > nodeMap
This maps each operation to its graph node.
Detailed Description
This graph tracks modules and where they are instantiated.
This is intended to be used as a cached analysis on FIRRTL circuits. This class can be used to walk the modules efficiently in a bottom-up or top-down order.
To use this class, retrieve a cached copy from the analysis manager: auto &instanceGraph = getAnalysis<InstanceGraph>(getOperation());
Definition at line 170 of file InstanceGraph.h.
Member Typedef Documentation
iterator
using circt::firrtl::InstanceGraph::iterator = detail::AddressIterator<NodeList::iterator>
Iterate through all modules.
Definition at line 205 of file InstanceGraph.h.
NodeList
using circt::firrtl::InstanceGraph::NodeList = llvm::iplist<InstanceGraphNode> private
This is the list of InstanceGraphNodes in the graph.
Definition at line 172 of file InstanceGraph.h.
Constructor & Destructor Documentation
InstanceGraph() [1/2]
InstanceGraph::InstanceGraph (Operation * operation) explicit
Create a new module graph of a circuit.
This must be called on a FIRRTL CircuitOp or MLIR ModuleOp.
Definition at line 53 of file InstanceGraph.cpp.
References getOrAddNode(), and topLevelNode.
InstanceGraph() [2/2]
circt::firrtl::InstanceGraph::InstanceGraph (const InstanceGraph &) private delete
Member Function Documentation
addModule()
InstanceGraphNode * InstanceGraph::addModule (FModuleLike module)
Add a newly created module to the instance graph.
Definition at line 79 of file InstanceGraph.cpp.
References nodeMap, and nodes.
begin()
iterator circt::firrtl::InstanceGraph::begin () inline
Definition at line 206 of file InstanceGraph.h.
References nodes.
Referenced by llvm::GraphTraits< circt::firrtl::InstanceGraph * >::nodes_begin().
end()
iterator circt::firrtl::InstanceGraph::end () inline
Definition at line 207 of file InstanceGraph.h.
References nodes.
Referenced by llvm::GraphTraits< circt::firrtl::InstanceGraph * >::nodes_end().
erase()
void InstanceGraph::erase (InstanceGraphNode * node)
Remove this module from the instance graph.
This will also remove all InstanceRecords in this module. All instances of this module must have been removed from the graph.
Definition at line 88 of file InstanceGraph.cpp.
References circt::firrtl::InstanceGraphNode::getModule(), nodeMap, nodes, and circt::firrtl::InstanceGraphNode::noUses().
getOrAddNode()
InstanceGraphNode * InstanceGraph::getOrAddNode (StringAttr name) private
Get the node corresponding to the module.
If the node has does not exist yet, it will be created.
Definition at line 42 of file InstanceGraph.cpp.
References nodeMap, and nodes.
Referenced by InstanceGraph().
getReferencedModule()
Operation * InstanceGraph::getReferencedModule (InstanceOp op)
Look up the referenced module from an InstanceOp.
This will use a hashtable lookup to find the module, where InstanceOp.getReferencedModule() will be a linear search through the IR.
Definition at line 114 of file InstanceGraph.cpp.
References circt::firrtl::InstanceGraphNode::getModule(), and lookup().
getSublistAccessgetSublistAccess()
static NodeList InstanceGraph::* circt::firrtl::InstanceGraph::getSublistAccessgetSublistAccess (Operation *) inline static
Returns pointer to member of operation list.
Definition at line 231 of file InstanceGraph.h.
References nodes.
getTopLevelModule()
FModuleLike InstanceGraph::getTopLevelModule ()
Get the module corresponding to the top-lebel module of a circuit.
Definition at line 100 of file InstanceGraph.cpp.
References circt::firrtl::InstanceGraphNode::getModule(), and getTopLevelNode().
getTopLevelNode()
InstanceGraphNode * InstanceGraph::getTopLevelNode ()
Get the node corresponding to the top-level module of a circuit.
Definition at line 98 of file InstanceGraph.cpp.
References topLevelNode.
Referenced by circt::firrtl::InstancePathCache::getAbsolutePaths(), llvm::GraphTraits< circt::firrtl::InstanceGraph * >::getEntryNode(), and getTopLevelModule().
isAncestor()
bool InstanceGraph::isAncestor (FModuleLike child, FModuleOp parent)
Check if child is instantiated by a parent.
Definition at line 134 of file InstanceGraph.cpp.
References lookup().
lookup() [1/2]
InstanceGraphNode * InstanceGraph::lookup (Operation * op)
Look up an InstanceGraphNode for a module.
Operation must be an FModuleOp or an FExtModuleOp.
Definition at line 110 of file InstanceGraph.cpp.
Referenced by getReferencedModule(), isAncestor(), operator[](), and replaceInstance().
lookup() [2/2]
InstanceGraphNode * InstanceGraph::lookup (StringAttr name)
Lookup an module by name.
Definition at line 104 of file InstanceGraph.cpp.
References nodeMap.
operator[]()
InstanceGraphNode* circt::firrtl::InstanceGraph::operator[] (Operation * op) inline
Lookup an InstanceGraphNode for a module.
Operation must be an FModuleOp or an FExtModuleOp.
Definition at line 194 of file InstanceGraph.h.
References lookup().
replaceInstance()
void InstanceGraph::replaceInstance (InstanceOp inst, InstanceOp newInst)
Replaces an instance of a module with another instance.
The target module of both InstanceOps must be the same.
Definition at line 118 of file InstanceGraph.cpp.
References lookup().
Member Data Documentation
nodeMap
llvm::DenseMap<Attribute, InstanceGraphNode *> circt::firrtl::InstanceGraph::nodeMap private
This maps each operation to its graph node.
Definition at line 248 of file InstanceGraph.h.
Referenced by addModule(), erase(), getOrAddNode(), and lookup().
nodes
NodeList circt::firrtl::InstanceGraph::nodes private
The storage for graph nodes, with deterministic iteration.
Definition at line 245 of file InstanceGraph.h.
Referenced by addModule(), begin(), end(), erase(), getOrAddNode(), and getSublistAccessgetSublistAccess().
topLevelNode
InstanceGraphNode* circt::firrtl::InstanceGraph::topLevelNode private
Definition at line 238 of file InstanceGraph.h.
Referenced by getTopLevelNode(), and InstanceGraph().
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/InstanceGraph.h
lib/Dialect/FIRRTL/InstanceGraph.cpp