CIRCT: lib/Conversion/ExportVerilog/ExportVerilog.cpp File Reference
ExportVerilog.cpp File Reference
#include "circt/Conversion/ExportVerilog.h"
#include "../PassDetail.h"
#include "ExportVerilogInternals.h"
#include "RearrangableOStream.h"
#include "circt/Dialect/Comb/CombDialect.h"
#include "circt/Dialect/Comb/CombVisitors.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/HW/HWVisitors.h"
#include "circt/Dialect/SV/SVVisitors.h"
#include "circt/Support/LLVM.h"
#include "circt/Support/LoweringOptions.h"
#include "circt/Support/Path.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/Threading.h"
#include "mlir/Support/FileUtilities.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "export-verilog"
Functions
static Attribute getInt32Attr (MLIRContext *ctx, uint32_t value)
static bool isDuplicatableNullaryExpression (Operation *op)
Return true for nullary operations that are better emitted multiple times as inline expression (when they have multiple uses) rather than having a temporary wire.
static bool isDuplicatableExpression (Operation *op)
static StringRef getSymOpName (Operation *symOp)
Return the verilog name of the operations that can define a symbol.
StringRef getPortVerilogName (Operation *module, ssize_t portArgNum)
Return the verilog name of the port for the module.
StringRef getPortVerilogName (Operation *module, PortInfo port)
static int getBitWidthOrSentinel (Type type)
Return the width of the specified type in bits or -1 if it isn't supported.
static void getTypeDims (SmallVectorImpl< Attribute > &dims, Type type, Location loc)
Push this type's dimension into a vector.
static bool haveMatchingDims (Type a, Type b, Location loc)
True iff 'a' and 'b' have the same wire dims.
static bool isZeroBitType (Type type)
Return true if this is a zero bit type, e.g.
static Type stripUnpackedTypes (Type type)
Given a set of known nested types (those supported by this pass), strip off leading unpacked types.
static bool hasStructType (Type type)
Return true if type has a struct type as a subtype.
static StringRef getVerilogDeclWord (Operation *op, const LoweringOptions &options)
Return the word (e.g. "reg") in Verilog to declare the specified thing.
static void collectFileLineColLocs (Location loc, SmallPtrSet< Attribute, 8 > &locationSet)
Pull any FileLineCol locs out of the specified location and add it to the specified set.
static std::string getLocationInfoAsString (const SmallPtrSet< Operation *, 8 > &ops)
Return the location information as a (potentially empty) string.
static bool isOkToBitSelectFrom (Value v)
Most expressions are invalid to bit-select from in Verilog, but some things are ok.
static void emitDims (ArrayRef< Attribute > dims, raw_ostream &os, Location loc, ModuleEmitter &emitter)
Emit a list of dimensions.
static bool printPackedTypeImpl (Type type, raw_ostream &os, Location loc, SmallVectorImpl< Attribute > &dims, bool implicitIntType, bool singleBitDefaultType, ModuleEmitter &emitter)
Output the basic type that consists of packed and primitive types.
static Value isZeroExtension (Value value)
If the specified extension is a zero extended version of another value, return the shorter value, otherwise return null.
static bool isExpressionUnableToInline (Operation *op)
Return true if we are unable to ever inline the specified operation.
static bool isExpressionEmittedInline (Operation *op)
Return true if this expression should be emitted inline into any statement that uses it.
static bool isExpressionEmittedInlineIntoProceduralDeclaration (Operation *op, StmtEmitter &stmtEmitter)
Given an operation corresponding to a VerilogExpression, determine whether it is safe to emit inline into a 'localparam' or 'automatic logic' varaible initializer in a procedural region.
static void emitOperation (VerilogEmitterState &state, Operation *op)
static void prepareForEmission (ModuleOp module, const LoweringOptions &options)
Prepare the given MLIR module for emission.
static std::unique_ptr< llvm::ToolOutputFile > createOutputFile (StringRef fileName, StringRef dirname, SharedEmitterState &emitter)
static void createSplitOutputFile (StringAttr fileName, FileInfo &file, StringRef dirname, SharedEmitterState &emitter)
Variables
constexpr int INDENT_AMOUNT = 2
constexpr int SPACE_PER_INDENT_IN_EXPRESSION_FORMATTING = 8
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "export-verilog"
Definition at line 52 of file ExportVerilog.cpp.
Function Documentation
collectFileLineColLocs()
static void collectFileLineColLocs (Location loc, SmallPtrSet< Attribute, 8 > & locationSet) static
Pull any FileLineCol locs out of the specified location and add it to the specified set.
Definition at line 383 of file ExportVerilog.cpp.
Referenced by getLocationInfoAsString().
createOutputFile()
static std::unique_ptr<llvm::ToolOutputFile> createOutputFile (StringRef fileName, StringRef dirname, SharedEmitterState & emitter) static
Definition at line 4519 of file ExportVerilog.cpp.
References circt::appendPossiblyAbsolutePath().
Referenced by createSplitOutputFile().
createSplitOutputFile()
static void createSplitOutputFile (StringAttr fileName, FileInfo & file, StringRef dirname, SharedEmitterState & emitter) static
Definition at line 4545 of file ExportVerilog.cpp.
References createOutputFile().
emitDims()
static void emitDims (ArrayRef< Attribute > dims, raw_ostream & os, Location loc, ModuleEmitter & emitter) static
Emit a list of dimensions.
Definition at line 1040 of file ExportVerilog.cpp.
References circt::calyx::direction::get(), and getInt32Attr().
Referenced by printPackedTypeImpl().
emitOperation()
static void emitOperation (VerilogEmitterState & state, Operation * op) static
Definition at line 4348 of file ExportVerilog.cpp.
Referenced by circt::ExportVerilog::SharedEmitterState::emitOps().
getBitWidthOrSentinel()
static int getBitWidthOrSentinel (Type type) static
Return the width of the specified type in bits or -1 if it isn't supported.
Definition at line 234 of file ExportVerilog.cpp.
Referenced by buildInnerFIFO(), canonicalizeMux(), and canonicalizePrimOp().
getInt32Attr()
static Attribute getInt32Attr (MLIRContext * ctx, uint32_t value) static
Definition at line 103 of file ExportVerilog.cpp.
Referenced by emitDims(), getTypeDims(), and printPackedTypeImpl().
getLocationInfoAsString()
static std::string getLocationInfoAsString (const SmallPtrSet< Operation *, 8 > & ops) static
Return the location information as a (potentially empty) string.
Definition at line 395 of file ExportVerilog.cpp.
References collectFileLineColLocs().
getPortVerilogName() [1/2]
StringRef getPortVerilogName (Operation * module, PortInfo port)
Definition at line 210 of file ExportVerilog.cpp.
References circt::hw::getModuleNumInputs(), and getPortVerilogName().
getPortVerilogName() [2/2]
StringRef getPortVerilogName (Operation * module, ssize_t portArgNum)
Return the verilog name of the port for the module.
Definition at line 178 of file ExportVerilog.cpp.
References circt::hw::getModuleNumInputs().
Referenced by getPortVerilogName().
getSymOpName()
static StringRef getSymOpName (Operation * symOp) static
Return the verilog name of the operations that can define a symbol.
Except for <WireOp, RegOp, LocalParamOp, InstanceOp>, check global state getDeclarationVerilogName for them.
Definition at line 150 of file ExportVerilog.cpp.
References circt::hw::getVerilogModuleName(), and circt::hw::getVerilogModuleNameAttr().
getTypeDims()
static void getTypeDims (SmallVectorImpl< Attribute > & dims, Type type, Location loc) static
Push this type's dimension into a vector.
Definition at line 251 of file ExportVerilog.cpp.
References getInt32Attr().
Referenced by haveMatchingDims().
getVerilogDeclWord()
static StringRef getVerilogDeclWord (Operation * op, const LoweringOptions & options) static
Return the word (e.g. "reg") in Verilog to declare the specified thing.
Definition at line 334 of file ExportVerilog.cpp.
References circt::LoweringOptions::disallowLocalVariables, and hasStructType().
hasStructType()
static bool hasStructType (Type type) static
Return true if type has a struct type as a subtype.
Definition at line 324 of file ExportVerilog.cpp.
Referenced by getVerilogDeclWord().
haveMatchingDims()
static bool haveMatchingDims (Type a, Type b, Location loc) static
True iff 'a' and 'b' have the same wire dims.
Definition at line 280 of file ExportVerilog.cpp.
References getTypeDims().
Referenced by isExpressionUnableToInline().
isDuplicatableExpression()
static bool isDuplicatableExpression (Operation * op) static
Definition at line 132 of file ExportVerilog.cpp.
References isDuplicatableNullaryExpression().
Referenced by isExpressionEmittedInline(), and isExpressionUnableToInline().
isDuplicatableNullaryExpression()
static bool isDuplicatableNullaryExpression (Operation * op) static
Return true for nullary operations that are better emitted multiple times as inline expression (when they have multiple uses) rather than having a temporary wire.
This can only handle nullary expressions, because we don't want to replicate subtrees arbitrarily.
Definition at line 113 of file ExportVerilog.cpp.
References circt::ExportVerilog::isConstantExpression().
Referenced by isDuplicatableExpression().
isExpressionEmittedInline()
static bool isExpressionEmittedInline (Operation * op) static
Return true if this expression should be emitted inline into any statement that uses it.
Definition at line 2273 of file ExportVerilog.cpp.
References isDuplicatableExpression(), and isExpressionUnableToInline().
Referenced by isExpressionEmittedInlineIntoProceduralDeclaration().
isExpressionEmittedInlineIntoProceduralDeclaration()
static bool isExpressionEmittedInlineIntoProceduralDeclaration (Operation * op, StmtEmitter & stmtEmitter) static
Given an operation corresponding to a VerilogExpression, determine whether it is safe to emit inline into a 'localparam' or 'automatic logic' varaible initializer in a procedural region.
We can't emit exprs inline when they refer to something else that can't be emitted inline, when they're in a general #ifdef region,
Definition at line 3587 of file ExportVerilog.cpp.
References isExpressionEmittedInline(), and circt::ExportVerilog::isVerilogExpression().
isExpressionUnableToInline()
static bool isExpressionUnableToInline (Operation * op) static
Return true if we are unable to ever inline the specified operation.
This happens because not all Verilog expressions are composable, notably you can only use bit selects like x[4:6] on simple expressions, you cannot use expressions in the sensitivity list of always blocks, etc.
Definition at line 2213 of file ExportVerilog.cpp.
References haveMatchingDims(), isDuplicatableExpression(), and isOkToBitSelectFrom().
Referenced by isExpressionEmittedInline().
isOkToBitSelectFrom()
static bool isOkToBitSelectFrom (Value v) static
Most expressions are invalid to bit-select from in Verilog, but some things are ok.
Return true if it is ok to inline bitselect from the result of this expression. It is conservatively correct to return false.
Definition at line 489 of file ExportVerilog.cpp.
Referenced by isExpressionUnableToInline().
isZeroBitType()
static bool isZeroBitType (Type type) static
Return true if this is a zero bit type, e.g.
a zero bit integer or array thereof.
Definition at line 292 of file ExportVerilog.cpp.
isZeroExtension()
static Value isZeroExtension (Value value) static
If the specified extension is a zero extended version of another value, return the shorter value, otherwise return null.
Definition at line 1743 of file ExportVerilog.cpp.
References concat().
prepareForEmission()
static void prepareForEmission (ModuleOp module, const LoweringOptions & options) static
Prepare the given MLIR module for emission.
Definition at line 4436 of file ExportVerilog.cpp.
printPackedTypeImpl()
static bool printPackedTypeImpl (Type type, raw_ostream & os, Location loc, SmallVectorImpl< Attribute > & dims, bool implicitIntType, bool singleBitDefaultType, ModuleEmitter & emitter) static
Output the basic type that consists of packed and primitive types.
This is those to the left of the name in verilog. implicitIntType controls whether to print a base type for (logic) for inteters or whether the caller will have handled this (with logic, wire, reg, etc).
Returns true when anything was printed out.
Definition at line 1080 of file ExportVerilog.cpp.
References emitDims(), getInt32Attr(), and stripUnpackedTypes().
stripUnpackedTypes()
static Type stripUnpackedTypes (Type type) static
Given a set of known nested types (those supported by this pass), strip off leading unpacked types.
This strips off portions of the type that are printed to the right of the name in verilog.
Definition at line 312 of file ExportVerilog.cpp.
Referenced by printPackedTypeImpl().
Variable Documentation
INDENT_AMOUNT
constexpr int INDENT_AMOUNT = 2 constexpr
Definition at line 54 of file ExportVerilog.cpp.
SPACE_PER_INDENT_IN_EXPRESSION_FORMATTING
constexpr int SPACE_PER_INDENT_IN_EXPRESSION_FORMATTING = 8 constexpr
Definition at line 55 of file ExportVerilog.cpp.