CIRCT: lib/Dialect/Handshake/HandshakeOps.cpp File Reference
HandshakeOps.cpp File Reference
#include "circt/Dialect/Handshake/HandshakeOps.h"
#include "circt/Support/LLVM.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Value.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include <set>
#include "circt/Dialect/Handshake/HandshakeCanonicalization.h.inc"
#include "circt/Dialect/Handshake/Handshake.cpp.inc"
Namespaces
circt
circt::handshake
sost
Macros
#define GET_OP_CLASSES
Functions
static std::string defaultOperandName (unsigned int idx)
void sost::addAttributes (OperationState &result, int size, Type dataType, bool alwaysControl=false)
static ParseResult sost::parseIntInSquareBrackets (OpAsmParser &parser, int &v)
static ParseResult sost::parseOperation (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::OperandType > &operands, OperationState &result, int &size, Type &type, bool explicitSize, bool alwaysControl=false)
static void sost::printOp (OpAsmPrinter &p, Operation *op, bool explicitSize)
static ParseResult parseForkOp (OpAsmParser &parser, OperationState &result)
static Value getDematerialized (Value v)
Returns a dematerialized version of the value 'v', defined as the source of the value before passing through a buffer or fork operation.
static ParseResult parseFuncOpArgs (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::OperandType > &entryArgs, SmallVectorImpl< Type > &argTypes, SmallVectorImpl< Attribute > &argNames, SmallVectorImpl< NamedAttrList > &argAttrs, SmallVectorImpl< Type > &resTypes, SmallVectorImpl< NamedAttrList > &resAttrs)
Parses a FuncOp signature using mlir::function_interface_impl::parseFunctionSignature while getting access to the parsed SSA names to store as attributes.
static SmallVector< Attribute > getFuncOpNames (Builder &builder, TypeRange types, StringRef prefix)
Generates names for a handshake.func input and output arguments, based on the number of args as well as a prefix.
static void addStringToStringArrayAttr (Builder &builder, Operation *op, StringRef attrName, StringAttr str)
Helper function for appending a string to an array attribute, and rewriting the attribute back to the operation.
static void setupSourceOp (OperationState &result)
static std::string getMemoryOperandName (unsigned nStores, unsigned idx)
static std::string getMemoryResultName (unsigned nLoads, unsigned nStores, unsigned idx)
static ParseResult parseMemoryAccessOp (OpAsmParser &parser, OperationState &result)
template<typename MemOp >
static void printMemoryAccessOp (OpAsmPrinter &p, MemOp op)
template<typename TMemoryOp >
static LogicalResult verifyMemoryAccessOp (TMemoryOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1484 of file HandshakeOps.cpp.
Function Documentation
addStringToStringArrayAttr()
static void addStringToStringArrayAttr (Builder & builder, Operation * op, StringRef attrName, StringAttr str) static
Helper function for appending a string to an array attribute, and rewriting the attribute back to the operation.
Definition at line 594 of file HandshakeOps.cpp.
defaultOperandName()
static std::string defaultOperandName (unsigned int idx) static
Definition at line 42 of file HandshakeOps.cpp.
getDematerialized()
static Value getDematerialized (Value v) static
Returns a dematerialized version of the value 'v', defined as the source of the value before passing through a buffer or fork operation.
Definition at line 281 of file HandshakeOps.cpp.
getFuncOpNames()
static SmallVector<Attribute> getFuncOpNames (Builder & builder, TypeRange types, StringRef prefix) static
Generates names for a handshake.func input and output arguments, based on the number of args as well as a prefix.
Definition at line 557 of file HandshakeOps.cpp.
References circt::esi::types.
getMemoryOperandName()
static std::string getMemoryOperandName (unsigned nStores, unsigned idx) static
Definition at line 1075 of file HandshakeOps.cpp.
getMemoryResultName()
static std::string getMemoryResultName (unsigned nLoads, unsigned nStores, unsigned idx) static
Definition at line 1092 of file HandshakeOps.cpp.
parseForkOp()
static ParseResult parseForkOp (OpAsmParser & parser, OperationState & result) static
Definition at line 118 of file HandshakeOps.cpp.
References sost::parseOperation(), and size().
parseFuncOpArgs()
static ParseResult parseFuncOpArgs (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::OperandType > & entryArgs, SmallVectorImpl< Type > & argTypes, SmallVectorImpl< Attribute > & argNames, SmallVectorImpl< NamedAttrList > & argAttrs, SmallVectorImpl< Type > & resTypes, SmallVectorImpl< NamedAttrList > & resAttrs) static
Parses a FuncOp signature using mlir::function_interface_impl::parseFunctionSignature while getting access to the parsed SSA names to store as attributes.
Definition at line 530 of file HandshakeOps.cpp.
References circt::calyx::direction::get().
parseMemoryAccessOp()
static ParseResult parseMemoryAccessOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1319 of file HandshakeOps.cpp.
References circt::calyx::direction::get().
printMemoryAccessOp()
template<typename MemOp > static void printMemoryAccessOp (OpAsmPrinter & p, MemOp op) static
Definition at line 1348 of file HandshakeOps.cpp.
setupSourceOp()
static void setupSourceOp (OperationState & result) static
Definition at line 940 of file HandshakeOps.cpp.
References sost::addAttributes(), and circt::calyx::direction::get().
verifyMemoryAccessOp()
template<typename TMemoryOp > static LogicalResult verifyMemoryAccessOp (TMemoryOp op) static
Definition at line 1375 of file HandshakeOps.cpp.