CIRCT: lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp File Reference
LowerAnnotations.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/CHIRRTLDialect.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotations.h"
#include "circt/Dialect/FIRRTL/FIRRTLAttributes.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/Namespace.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "mlir/IR/Diagnostics.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/StringExtras.h"
Functions
static bool hasName (StringRef name, Operation *op)
Abstraction over namable things. Do they have names?
static AnnoTarget findNamedThing (StringRef name, Operation *op)
Find a matching name in an operation (usually FModuleOp).
static ArrayAttr getAnnotationsFrom (Operation *op)
Get annotations or an empty set of annotations.
static ArrayAttr appendArrayAttr (ArrayAttr array, Attribute a)
Construct the annotation array with a new thing appended.
static ArrayAttr replaceArrayAttrElement (ArrayAttr array, size_t elem, Attribute newVal)
Update an ArrayAttribute by replacing one entry.
static void addAnnotation (AnnoTarget ref, unsigned fieldIdx, ArrayRef< NamedAttribute > anno)
Apply a new annotation to a resolved target.
static LogicalResult updateExpandedPort (StringRef field, AnnoTarget &ref)
static FailureOr< unsigned > findBundleElement (Operation *op, Type type, StringRef field)
Try to resolve an non-array aggregate name from a target given the type and operation of the resolved target.
static FailureOr< unsigned > findVectorElement (Operation *op, Type type, StringRef indexStr)
Try to resolve an array index from a target given the type of the resolved target.
static FailureOr< unsigned > findFieldID (AnnoTarget &ref, ArrayRef< TargetToken > tokens)
Optional< AnnoPathValue > resolveEntities (TokenAnnoTarget path, ApplyState &state)
Convert a parsed target string to a resolved target structure.
static std::string canonicalizeTarget (StringRef target)
Return an input target string in canonical form.
static Optional< TokenAnnoTarget > tokenizePath (StringRef origTarget)
split a target string into it constituent parts.
static FlatSymbolRefAttr buildNLA (AnnoPathValue target, ApplyState &state)
Make an anchor for a non-local annotation.
static FlatSymbolRefAttr scatterNonLocalPath (AnnoPathValue target, ApplyState &state)
Scatter breadcrumb annotations corresponding to non-local annotations along the instance path.
static Optional< AnnoPathValue > noResolve (DictionaryAttr anno, ApplyState &state)
Always resolve to the circuit, ignoring the annotation.
static Optional< AnnoPathValue > stdResolveImpl (StringRef rawPath, ApplyState &state)
Implementation of standard resolution.
static Optional< AnnoPathValue > stdResolve (DictionaryAttr anno, ApplyState &state)
(SFC) FIRRTL SingleTargetAnnotation resolver.
static Optional< AnnoPathValue > tryResolve (DictionaryAttr anno, ApplyState &state)
Resolves with target, if it exists. If not, resolves to the circuit.
static LogicalResult applyWithoutTargetImpl (AnnoPathValue target, DictionaryAttr anno, ApplyState &state, bool allowNonLocal)
An applier which puts the annotation on the target and drops the 'target' field from the annotaiton.
template<bool allowNonLocal, typename T , typename... Tr>
static LogicalResult applyWithoutTarget (AnnoPathValue target, DictionaryAttr anno, ApplyState &state)
An applier which puts the annotation on the target and drops the 'target' field from the annotaiton.
template<bool allowNonLocal = false>
static LogicalResult applyWithoutTarget (AnnoPathValue target, DictionaryAttr anno, ApplyState &state)
An applier which puts the annotation on the target and drops the 'target' field from the annotaiton.
static const AnnoRecord * getAnnotationHandler (StringRef annoStr, bool ignoreUnhandledAnno)
Lookup a record for a given annotation class.
Variables
static const llvm::StringMap< AnnoRecord > annotationRecords
Function Documentation
addAnnotation()
static void addAnnotation (AnnoTarget ref, unsigned fieldIdx, ArrayRef< NamedAttribute > anno) static
Apply a new annotation to a resolved target.
This handles ports, aggregates, modules, wires, etc.
Definition at line 159 of file LowerAnnotations.cpp.
References appendArrayAttr(), circt::calyx::direction::get(), circt::firrtl::getAnnotationAttrName(), getAnnotationsFrom(), circt::firrtl::getNumPorts(), circt::firrtl::getPortAnnotationAttrName(), and replaceArrayAttrElement().
Referenced by applyWithoutTargetImpl(), and scatterNonLocalPath().
appendArrayAttr()
static ArrayAttr appendArrayAttr (ArrayAttr array, Attribute a) static
Construct the annotation array with a new thing appended.
Definition at line 141 of file LowerAnnotations.cpp.
References circt::calyx::direction::get().
Referenced by addAnnotation().
applyWithoutTarget() [1/2]
template<bool allowNonLocal, typename T , typename... Tr> static LogicalResult applyWithoutTarget (AnnoPathValue target, DictionaryAttr anno, ApplyState & state) static
An applier which puts the annotation on the target and drops the 'target' field from the annotaiton.
Optionally handles non-local annotations. Ensures the target resolves to an expected type of operation.
Definition at line 561 of file LowerAnnotations.cpp.
References applyWithoutTargetImpl().
applyWithoutTarget() [2/2]
template<bool allowNonLocal = false> static LogicalResult applyWithoutTarget (AnnoPathValue target, DictionaryAttr anno, ApplyState & state) static
An applier which puts the annotation on the target and drops the 'target' field from the annotaiton.
Optionally handles non-local annotations.
Definition at line 572 of file LowerAnnotations.cpp.
References applyWithoutTargetImpl().
applyWithoutTargetImpl()
static LogicalResult applyWithoutTargetImpl (AnnoPathValue target, DictionaryAttr anno, ApplyState & state, bool allowNonLocal) static
An applier which puts the annotation on the target and drops the 'target' field from the annotaiton.
Optionally handles non-local annotations.
Definition at line 537 of file LowerAnnotations.cpp.
References addAnnotation(), circt::calyx::direction::get(), and scatterNonLocalPath().
Referenced by applyWithoutTarget().
buildNLA()
static FlatSymbolRefAttr buildNLA (AnnoPathValue target, ApplyState & state) static
Make an anchor for a non-local annotation.
Use the expanded path to build the module and name list in the anchor.
Definition at line 439 of file LowerAnnotations.cpp.
References circt::calyx::direction::get().
Referenced by scatterNonLocalPath().
canonicalizeTarget()
static std::string canonicalizeTarget (StringRef target) static
Return an input target string in canonical form.
This converts a Legacy Annotation (e.g., A.B.C) into a modern annotation (e.g., ~A|B>C). Trailing subfield/subindex references are preserved.
Definition at line 372 of file LowerAnnotations.cpp.
Referenced by stdResolveImpl().
findBundleElement()
static FailureOr<unsigned> findBundleElement (Operation * op, Type type, StringRef field) static
Try to resolve an non-array aggregate name from a target given the type and operation of the resolved target.
This needs to deal with places where we represent bundle returns as split into constituent parts.
Definition at line 212 of file LowerAnnotations.cpp.
Referenced by findFieldID().
findFieldID()
static FailureOr<unsigned> findFieldID (AnnoTarget & ref, ArrayRef< TargetToken > tokens) static
Definition at line 247 of file LowerAnnotations.cpp.
References findBundleElement(), findVectorElement(), and updateExpandedPort().
Referenced by resolveEntities().
findNamedThing()
static AnnoTarget findNamedThing (StringRef name, Operation * op) static
Find a matching name in an operation (usually FModuleOp).
This walk could be cached in the future. This finds a port or operation for a given name.
Definition at line 110 of file LowerAnnotations.cpp.
References hasName().
Referenced by resolveEntities().
findVectorElement()
static FailureOr<unsigned> findVectorElement (Operation * op, Type type, StringRef indexStr) static
Try to resolve an array index from a target given the type of the resolved target.
Definition at line 231 of file LowerAnnotations.cpp.
Referenced by findFieldID().
getAnnotationHandler()
static const AnnoRecord* getAnnotationHandler (StringRef annoStr, bool ignoreUnhandledAnno) static
Lookup a record for a given annotation class.
Optionally, returns the record for "circuit.missing" if the record doesn't exist.
Definition at line 602 of file LowerAnnotations.cpp.
References annotationRecords.
getAnnotationsFrom()
static ArrayAttr getAnnotationsFrom (Operation * op) static
Get annotations or an empty set of annotations.
Definition at line 134 of file LowerAnnotations.cpp.
References circt::calyx::direction::get(), and circt::firrtl::getAnnotationAttrName().
Referenced by addAnnotation().
hasName()
static bool hasName (StringRef name, Operation * op) static
Abstraction over namable things. Do they have names?
Definition at line 100 of file LowerAnnotations.cpp.
Referenced by findNamedThing().
noResolve()
static Optional<AnnoPathValue> noResolve (DictionaryAttr anno, ApplyState & state) static
Always resolve to the circuit, ignoring the annotation.
Definition at line 480 of file LowerAnnotations.cpp.
replaceArrayAttrElement()
static ArrayAttr replaceArrayAttrElement (ArrayAttr array, size_t elem, Attribute newVal) static
Update an ArrayAttribute by replacing one entry.
Definition at line 150 of file LowerAnnotations.cpp.
References circt::calyx::direction::get().
Referenced by addAnnotation().
resolveEntities()
Optional<AnnoPathValue> resolveEntities (TokenAnnoTarget path, ApplyState & state)
Convert a parsed target string to a resolved target structure.
This resolves all names and aggregates from a parsed target.
Definition at line 284 of file LowerAnnotations.cpp.
References findFieldID(), and findNamedThing().
Referenced by stdResolveImpl().
scatterNonLocalPath()
static FlatSymbolRefAttr scatterNonLocalPath (AnnoPathValue target, ApplyState & state) static
Scatter breadcrumb annotations corresponding to non-local annotations along the instance path.
Returns symbol name used to anchor annotations to path.
Definition at line 460 of file LowerAnnotations.cpp.
References addAnnotation(), buildNLA(), and circt::calyx::direction::get().
Referenced by applyWithoutTargetImpl().
stdResolve()
static Optional<AnnoPathValue> stdResolve (DictionaryAttr anno, ApplyState & state) static
(SFC) FIRRTL SingleTargetAnnotation resolver.
Uses the 'target' field of the annotation with standard parsing to resolve the path. This requires 'target' to exist and be normalized (per docs/FIRRTLAnnotations.md).
Definition at line 504 of file LowerAnnotations.cpp.
References stdResolveImpl().
stdResolveImpl()
static Optional<AnnoPathValue> stdResolveImpl (StringRef rawPath, ApplyState & state) static
Implementation of standard resolution.
First parses the target path, then resolves it.
Definition at line 487 of file LowerAnnotations.cpp.
References canonicalizeTarget(), resolveEntities(), and tokenizePath().
Referenced by stdResolve(), and tryResolve().
tokenizePath()
static Optional<TokenAnnoTarget> tokenizePath (StringRef origTarget) static
split a target string into it constituent parts.
This is the primary parser for targets.
Definition at line 400 of file LowerAnnotations.cpp.
Referenced by stdResolveImpl().
tryResolve()
static Optional<AnnoPathValue> tryResolve (DictionaryAttr anno, ApplyState & state) static
Resolves with target, if it exists. If not, resolves to the circuit.
Definition at line 522 of file LowerAnnotations.cpp.
References stdResolveImpl().
updateExpandedPort()
static LogicalResult updateExpandedPort (StringRef field, AnnoTarget & ref) static
Definition at line 198 of file LowerAnnotations.cpp.
Referenced by findFieldID().
Variable Documentation
annotationRecords
const llvm::StringMap<AnnoRecord> annotationRecords static
Initial value:
{{
    {"circt.test", {stdResolve, applyWithoutTarget<true>}},
    {"circt.testNT", {noResolve, applyWithoutTarget<>}},
    {"circt.missing", {tryResolve, applyWithoutTarget<>}}
}}
Definition at line 591 of file LowerAnnotations.cpp.
Referenced by getAnnotationHandler().