CIRCT: lib/Conversion/FIRRTLToHW/LowerToHW.cpp File Reference
LowerToHW.cpp File Reference
#include "../PassDetail.h"
#include "circt/Conversion/FIRRTLToHW.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotations.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/InstanceGraph.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/HW/Namespace.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Support/Namespace.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/Threading.h"
#include "mlir/Pass/Pass.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/Parallel.h"
Functions
static Type lowerType (Type type)
Given a FIRRTL type, return the corresponding type for the HW dialect.
static LogicalResult verifyOpLegality (Operation *op)
This verifies that the target operation has been lowered to a legal operation.
static IntType getWidestIntType (Type t1, Type t2)
Given two FIRRTL integer types, return the widest one.
static Value castToFIRRTLType (Value val, Type type, ImplicitLocOpBuilder &builder)
Cast from a standard type to a FIRRTL type, potentially with a flip.
static Value castFromFIRRTLType (Value val, Type type, ImplicitLocOpBuilder &builder)
Cast from a FIRRTL type (potentially with a flip) to a standard type.
static bool isZeroBitFIRRTLType (Type type)
Return true if the specified FIRRTL type is a sized type (Int or Analog) with zero bits.
static void moveVerifAnno (ModuleOp top, AnnotationSet &annos, StringRef annoClass, StringRef attrBase)
Move a ExtractTestCode related annotation from annotations to an attribute.
static SmallVector< FirMemory > collectFIRRTLMemories (FModuleOp module)
static SmallVector< FirMemory > mergeFIRRTLMemories (const SmallVector< FirMemory > &lhs, SmallVector< FirMemory > rhs)
static unsigned getBitWidthFromVectorSize (unsigned size)
static void tryCopyName (Operation *dst, Operation *src)
static ArrayAttr getHWParameters (FExtModuleOp module, bool ignoreValues)
Map the parameter specifier on the specified extmodule into the HWModule representation for parameters.
static Value tryEliminatingAttachesToAnalogValue (Value value, Operation *insertPoint)
Given a value of analog type, check to see the only use of it is an attach.
static Value tryEliminatingConnectsToValue (Value flipValue, Operation *insertPoint)
Given a value of flip type, check to see if all of the uses of it are connects.
static SmallVector< SubfieldOp > getAllFieldAccesses (Value structValue, StringRef field)
static LogicalResult handleZeroBit (Value failedOperand, std::function< LogicalResult()> fn)
Zero bit operands end up looking like failures from getLoweredValue.
template<typename... Args>
static Operation * buildImmediateVerifOp (ImplicitLocOpBuilder &builder, StringRef opName, Args &&...args)
Helper function to build an immediate assert operation based on the original FIRRTL operation name.
template<typename... Args>
static Operation * buildConcurrentVerifOp (ImplicitLocOpBuilder &builder, StringRef opName, Args &&...args)
Helper function to build a concurrent assert operation based on the original FIRRTL operation name.
Variables
static const char assertAnnoClass []
static const char assumeAnnoClass []
static const char coverAnnoClass []
static const char dutAnnoClass [] = "sifive.enterprise.firrtl.MarkDUTAnnotation"
static const char moduleHierAnnoClass []
static const char testbenchDirAnnoClass []
static const char testHarnessHierAnnoClass []
static const char verifBBClass []
static const char forceNameClass []
static const char moduleHierarchyFileAttrName [] = "firrtl.moduleHierarchyFile"
Attribute that indicates that the module hierarchy starting at the annotated module should be dumped to a file.
static const char metadataDirectoryAttrName []
Attribute that indicates where some json files should be dumped.
Function Documentation
buildConcurrentVerifOp()
template<typename... Args> static Operation* buildConcurrentVerifOp (ImplicitLocOpBuilder & builder, StringRef opName, Args &&... args) static
Helper function to build a concurrent assert operation based on the original FIRRTL operation name.
This reduces code duplication in lowerVerificationStatement.
Definition at line 3638 of file LowerToHW.cpp.
buildImmediateVerifOp()
template<typename... Args> static Operation* buildImmediateVerifOp (ImplicitLocOpBuilder & builder, StringRef opName, Args &&... args) static
Helper function to build an immediate assert operation based on the original FIRRTL operation name.
This reduces code duplication in lowerVerificationStatement.
Definition at line 3623 of file LowerToHW.cpp.
castFromFIRRTLType()
static Value castFromFIRRTLType (Value val, Type type, ImplicitLocOpBuilder & builder) static
Cast from a FIRRTL type (potentially with a flip) to a standard type.
Definition at line 163 of file LowerToHW.cpp.
References circt::firrtl::getPassiveType().
Referenced by tryEliminatingAttachesToAnalogValue(), and tryEliminatingConnectsToValue().
castToFIRRTLType()
static Value castToFIRRTLType (Value val, Type type, ImplicitLocOpBuilder & builder) static
Cast from a standard type to a FIRRTL type, potentially with a flip.
Definition at line 147 of file LowerToHW.cpp.
collectFIRRTLMemories()
static SmallVector<FirMemory> collectFIRRTLMemories (FModuleOp module) static
Definition at line 215 of file LowerToHW.cpp.
getAllFieldAccesses()
static SmallVector<SubfieldOp> getAllFieldAccesses (Value structValue, StringRef field) static
Definition at line 1174 of file LowerToHW.cpp.
getBitWidthFromVectorSize()
static unsigned getBitWidthFromVectorSize (unsigned size) static
Definition at line 236 of file LowerToHW.cpp.
References size().
getHWParameters()
static ArrayAttr getHWParameters (FExtModuleOp module, bool ignoreValues) static
Map the parameter specifier on the specified extmodule into the HWModule representation for parameters.
If ignoreValues is true, all the values are dropped.
Definition at line 907 of file LowerToHW.cpp.
References circt::calyx::direction::get().
getWidestIntType()
static IntType getWidestIntType (Type t1, Type t2) static
Given two FIRRTL integer types, return the widest one.
Definition at line 141 of file LowerToHW.cpp.
References circt::firrtl::IntType::getWidth().
handleZeroBit()
static LogicalResult handleZeroBit (Value failedOperand, std::function< LogicalResult()> fn) static
Zero bit operands end up looking like failures from getLoweredValue.
This helper function invokes the closure specified if the operand was actually zero bit, or returns failure() if it was some other kind of failure.
Definition at line 1669 of file LowerToHW.cpp.
References isZeroBitFIRRTLType().
isZeroBitFIRRTLType()
static bool isZeroBitFIRRTLType (Type type) static
Return true if the specified FIRRTL type is a sized type (Int or Analog) with zero bits.
Definition at line 184 of file LowerToHW.cpp.
References circt::firrtl::getPassiveType().
Referenced by handleZeroBit().
lowerType()
static Type lowerType (Type type) static
Given a FIRRTL type, return the corresponding type for the HW dialect.
This returns a null type if it cannot be lowered.
Definition at line 69 of file LowerToHW.cpp.
References circt::calyx::direction::get(), and circt::firrtl::FIRRTLType::getPassiveType().
Referenced by tryEliminatingAttachesToAnalogValue(), and tryEliminatingConnectsToValue().
mergeFIRRTLMemories()
static SmallVector<FirMemory> mergeFIRRTLMemories (const SmallVector< FirMemory > & lhs, SmallVector< FirMemory > rhs) static
Definition at line 223 of file LowerToHW.cpp.
moveVerifAnno()
static void moveVerifAnno (ModuleOp top, AnnotationSet & annos, StringRef annoClass, StringRef attrBase) static
Move a ExtractTestCode related annotation from annotations to an attribute.
Definition at line 189 of file LowerToHW.cpp.
References circt::calyx::direction::get(), and circt::firrtl::AnnotationSet::getAnnotation().
tryCopyName()
static void tryCopyName (Operation * dst, Operation * src) static
Definition at line 242 of file LowerToHW.cpp.
tryEliminatingAttachesToAnalogValue()
static Value tryEliminatingAttachesToAnalogValue (Value value, Operation * insertPoint) static
Given a value of analog type, check to see the only use of it is an attach.
If so, remove the attach and return the value being attached to it, converted to an HW inout type. If this isn't a situation we can handle, just return null.
Definition at line 1068 of file LowerToHW.cpp.
References castFromFIRRTLType(), circt::calyx::direction::get(), and lowerType().
Referenced by tryEliminatingConnectsToValue().
tryEliminatingConnectsToValue()
static Value tryEliminatingConnectsToValue (Value flipValue, Operation * insertPoint) static
Given a value of flip type, check to see if all of the uses of it are connects.
If so, remove the connects and return the value being connected to it, converted to an HW type. If this isn't a situation we can handle, just return null.
This can happen when there are no connects to the value. The 'mergePoint' location is where a 'hw.merge' operation should be inserted if needed.
Definition at line 1104 of file LowerToHW.cpp.
References castFromFIRRTLType(), circt::firrtl::FIRRTLType::getBitWidthOrSentinel(), circt::firrtl::getPassiveType(), circt::firrtl::FIRRTLType::isPassive(), lowerType(), and tryEliminatingAttachesToAnalogValue().
verifyOpLegality()
static LogicalResult verifyOpLegality (Operation * op) static
This verifies that the target operation has been lowered to a legal operation.
This checks that the operation recursively has no FIRRTL operations or types.
Definition at line 104 of file LowerToHW.cpp.
References circt::esi::types.
Variable Documentation
assertAnnoClass
const char assertAnnoClass[] static
Initial value:
=
    "sifive.enterprise.firrtl.ExtractAssertionsAnnotation"
Definition at line 41 of file LowerToHW.cpp.
assumeAnnoClass
const char assumeAnnoClass[] static
Initial value:
=
    "sifive.enterprise.firrtl.ExtractAssumptionsAnnotation"
Definition at line 43 of file LowerToHW.cpp.
coverAnnoClass
const char coverAnnoClass[] static
Initial value:
=
    "sifive.enterprise.firrtl.ExtractCoverageAnnotation"
Definition at line 45 of file LowerToHW.cpp.
dutAnnoClass
const char dutAnnoClass[] = "sifive.enterprise.firrtl.MarkDUTAnnotation" static
Definition at line 47 of file LowerToHW.cpp.
forceNameClass
const char forceNameClass[] static
Initial value:
=
    "chisel3.util.experimental.ForceNameAnnotation"
Definition at line 56 of file LowerToHW.cpp.
metadataDirectoryAttrName
const char metadataDirectoryAttrName[] static
Initial value:
=
    "sifive.enterprise.firrtl.MetadataDirAnnotation"
Attribute that indicates where some json files should be dumped.
Definition at line 64 of file LowerToHW.cpp.
moduleHierAnnoClass
const char moduleHierAnnoClass[] static
Initial value:
=
    "sifive.enterprise.firrtl.ModuleHierarchyAnnotation"
Definition at line 48 of file LowerToHW.cpp.
moduleHierarchyFileAttrName
const char moduleHierarchyFileAttrName[] = "firrtl.moduleHierarchyFile" static
Attribute that indicates that the module hierarchy starting at the annotated module should be dumped to a file.
Definition at line 61 of file LowerToHW.cpp.
testbenchDirAnnoClass
const char testbenchDirAnnoClass[] static
Initial value:
=
    "sifive.enterprise.firrtl.TestBenchDirAnnotation"
Definition at line 50 of file LowerToHW.cpp.
testHarnessHierAnnoClass
const char testHarnessHierAnnoClass[] static
Initial value:
=
    "sifive.enterprise.firrtl.TestHarnessHierarchyAnnotation"
Definition at line 52 of file LowerToHW.cpp.
verifBBClass
const char verifBBClass[] static
Initial value:
=
    "freechips.rocketchip.annotations.InternalVerifBlackBoxAnnotation"
Definition at line 54 of file LowerToHW.cpp.