CIRCT: lib/CAPI/Dialect/MSFT.cpp File Reference
MSFT.cpp File Reference
#include "circt-c/Dialect/MSFT.h"
#include "circt/Dialect/HW/HWSymCache.h"
#include "circt/Dialect/MSFT/DeviceDB.h"
#include "circt/Dialect/MSFT/ExportTcl.h"
#include "circt/Dialect/MSFT/MSFTAttributes.h"
#include "circt/Dialect/MSFT/MSFTDialect.h"
#include "circt/Dialect/MSFT/MSFTOps.h"
#include "circt/Support/LLVM.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/CAPI/Support.h"
#include "mlir/CAPI/Utils.h"
#include "mlir/IR/Builders.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/raw_ostream.h"
Functions
void mlirMSFTRegisterPasses ()
CirctMSFTPrimitiveDB circtMSFTCreatePrimitiveDB (MlirContext ctxt)
void circtMSFTDeletePrimitiveDB (CirctMSFTPrimitiveDB self)
MlirLogicalResult circtMSFTPrimitiveDBAddPrimitive (CirctMSFTPrimitiveDB self, MlirAttribute cLoc)
bool circtMSFTPrimitiveDBIsValidLocation (CirctMSFTPrimitiveDB self, MlirAttribute cLoc)
CirctMSFTPlacementDB circtMSFTCreatePlacementDB (MlirModule top, CirctMSFTPrimitiveDB seed)
void circtMSFTDeletePlacementDB (CirctMSFTPlacementDB self)
MlirOperation circtMSFTPlacementDBPlace (CirctMSFTPlacementDB db, MlirOperation inst, MlirAttribute loc, MlirStringRef subpath, MlirLocation srcLoc)
void circtMSFTPlacementDBRemovePlacement (CirctMSFTPlacementDB db, MlirOperation locOp)
MlirLogicalResult circtMSFTPlacementDBMovePlacement (CirctMSFTPlacementDB db, MlirOperation locOp, MlirAttribute newLoc)
MlirOperation circtMSFTPlacementDBGetInstanceAt (CirctMSFTPlacementDB db, MlirAttribute loc)
MlirAttribute circtMSFTPlacementDBGetNearestFreeInColumn (CirctMSFTPlacementDB db, CirctMSFTPrimitiveType prim, uint64_t column, uint64_t nearestToY)
MLIR_CAPI_EXPORTED void circtMSFTPlacementDBWalkPlacements (CirctMSFTPlacementDB cdb, CirctMSFTPlacementCallback ccb, int64_t bounds[4], CirctMSFTPrimitiveType cPrimTypeFilter, CirctMSFTWalkOrder cWalkOrder, void *userData)
Walk all the placements within 'bounds' ([xmin, xmax, ymin, ymax], inclusive on all sides), with -1 meaning unbounded.
void mlirMSFTAddPhysLocationAttr (MlirOperation cOp, const char *entityName, PrimitiveType type, long x, long y, long num)
bool circtMSFTAttributeIsAPhysLocationAttribute (MlirAttribute attr)
MlirAttribute circtMSFTPhysLocationAttrGet (MlirContext cCtxt, CirctMSFTPrimitiveType devType, uint64_t x, uint64_t y, uint64_t num)
CirctMSFTPrimitiveType circtMSFTPhysLocationAttrGetPrimitiveType (MlirAttribute attr)
uint64_t circtMSFTPhysLocationAttrGetX (MlirAttribute attr)
uint64_t circtMSFTPhysLocationAttrGetY (MlirAttribute attr)
uint64_t circtMSFTPhysLocationAttrGetNum (MlirAttribute attr)
bool circtMSFTAttributeIsAPhysicalBoundsAttr (MlirAttribute attr)
MlirAttribute circtMSFTPhysicalBoundsAttrGet (MlirContext cContext, uint64_t xMin, uint64_t xMax, uint64_t yMin, uint64_t yMax)
MlirOperation circtMSFTGetInstance (MlirOperation cRoot, MlirAttribute cPath)
Function Documentation
circtMSFTAttributeIsAPhysicalBoundsAttr()
bool circtMSFTAttributeIsAPhysicalBoundsAttr (MlirAttribute attr)
Definition at line 174 of file MSFT.cpp.
circtMSFTAttributeIsAPhysLocationAttribute()
bool circtMSFTAttributeIsAPhysLocationAttribute (MlirAttribute attr)
Definition at line 145 of file MSFT.cpp.
circtMSFTCreatePlacementDB()
CirctMSFTPlacementDB circtMSFTCreatePlacementDB (MlirModule top, CirctMSFTPrimitiveDB seed)
Definition at line 61 of file MSFT.cpp.
Referenced by PlacementDB::PlacementDB().
circtMSFTCreatePrimitiveDB()
CirctMSFTPrimitiveDB circtMSFTCreatePrimitiveDB (MlirContext ctxt)
Definition at line 38 of file MSFT.cpp.
Referenced by PrimitiveDB::PrimitiveDB().
circtMSFTDeletePlacementDB()
void circtMSFTDeletePlacementDB (CirctMSFTPlacementDB self)
Definition at line 67 of file MSFT.cpp.
Referenced by PlacementDB::~PlacementDB().
circtMSFTDeletePrimitiveDB()
void circtMSFTDeletePrimitiveDB (CirctMSFTPrimitiveDB self)
Definition at line 41 of file MSFT.cpp.
Referenced by PrimitiveDB::~PrimitiveDB().
circtMSFTGetInstance()
MlirOperation circtMSFTGetInstance (MlirOperation cRoot, MlirAttribute cPath)
Definition at line 185 of file MSFT.cpp.
References circt::msft::getInstance().
circtMSFTPhysicalBoundsAttrGet()
MlirAttribute circtMSFTPhysicalBoundsAttrGet (MlirContext cContext, uint64_t xMin, uint64_t xMax, uint64_t yMin, uint64_t yMax)
Definition at line 178 of file MSFT.cpp.
References circt::calyx::direction::get().
circtMSFTPhysLocationAttrGet()
MlirAttribute circtMSFTPhysLocationAttrGet (MlirContext cCtxt, CirctMSFTPrimitiveType devType, uint64_t x, uint64_t y, uint64_t num)
Definition at line 148 of file MSFT.cpp.
References circt::calyx::direction::get().
circtMSFTPhysLocationAttrGetNum()
uint64_t circtMSFTPhysLocationAttrGetNum (MlirAttribute attr)
Definition at line 170 of file MSFT.cpp.
circtMSFTPhysLocationAttrGetPrimitiveType()
CirctMSFTPrimitiveType circtMSFTPhysLocationAttrGetPrimitiveType (MlirAttribute attr)
Definition at line 158 of file MSFT.cpp.
circtMSFTPhysLocationAttrGetX()
uint64_t circtMSFTPhysLocationAttrGetX (MlirAttribute attr)
Definition at line 164 of file MSFT.cpp.
circtMSFTPhysLocationAttrGetY()
uint64_t circtMSFTPhysLocationAttrGetY (MlirAttribute attr)
Definition at line 167 of file MSFT.cpp.
circtMSFTPlacementDBGetInstanceAt()
MlirOperation circtMSFTPlacementDBGetInstanceAt (CirctMSFTPlacementDB db, MlirAttribute loc)
Definition at line 90 of file MSFT.cpp.
Referenced by PlacementDB::getInstanceAt().
circtMSFTPlacementDBGetNearestFreeInColumn()
MlirAttribute circtMSFTPlacementDBGetNearestFreeInColumn (CirctMSFTPlacementDB db, CirctMSFTPrimitiveType prim, uint64_t column, uint64_t nearestToY)
Definition at line 94 of file MSFT.cpp.
Referenced by PlacementDB::getNearestFreeInColumn().
circtMSFTPlacementDBMovePlacement()
MlirLogicalResult circtMSFTPlacementDBMovePlacement (CirctMSFTPlacementDB db, MlirOperation locOp, MlirAttribute newLoc)
Definition at line 83 of file MSFT.cpp.
Referenced by PlacementDB::movePlacement().
circtMSFTPlacementDBPlace()
MlirOperation circtMSFTPlacementDBPlace (CirctMSFTPlacementDB db, MlirOperation inst, MlirAttribute loc, MlirStringRef subpath, MlirLocation srcLoc)
Definition at line 71 of file MSFT.cpp.
Referenced by PlacementDB::place().
circtMSFTPlacementDBRemovePlacement()
void circtMSFTPlacementDBRemovePlacement (CirctMSFTPlacementDB db, MlirOperation locOp)
Definition at line 79 of file MSFT.cpp.
Referenced by PlacementDB::removePlacement().
circtMSFTPlacementDBWalkPlacements()
MLIR_CAPI_EXPORTED void circtMSFTPlacementDBWalkPlacements (CirctMSFTPlacementDB cdb, CirctMSFTPlacementCallback ccb, int64_t bounds[4], CirctMSFTPrimitiveType cPrimTypeFilter, CirctMSFTWalkOrder cWalkOrder, void * userData)
Walk all the placements within 'bounds' ([xmin, xmax, ymin, ymax], inclusive on all sides), with -1 meaning unbounded.
Definition at line 104 of file MSFT.cpp.
References CirctMSFTWalkOrder::columns, NONE, CirctMSFTWalkOrder::rows, and circt::msft::PlacementDB::walkPlacements().
Referenced by PlacementDB::walkPlacements().
circtMSFTPrimitiveDBAddPrimitive()
MlirLogicalResult circtMSFTPrimitiveDBAddPrimitive (CirctMSFTPrimitiveDB self, MlirAttribute cLoc)
Definition at line 44 of file MSFT.cpp.
Referenced by PrimitiveDB::addPrimitive().
circtMSFTPrimitiveDBIsValidLocation()
bool circtMSFTPrimitiveDBIsValidLocation (CirctMSFTPrimitiveDB self, MlirAttribute cLoc)
Definition at line 49 of file MSFT.cpp.
Referenced by PrimitiveDB::isValidLocation().
mlirMSFTAddPhysLocationAttr()
void mlirMSFTAddPhysLocationAttr (MlirOperation cOp, const char * entityName, PrimitiveType type, long x, long y, long num)
Definition at line 133 of file MSFT.cpp.
References circt::calyx::direction::get().
mlirMSFTRegisterPasses()
void mlirMSFTRegisterPasses ()
Definition at line 27 of file MSFT.cpp.
References circt::msft::registerMSFTPasses().