CIRCT: circt::msft Namespace Reference
circt::msft Namespace Reference
Classes
class PlacementDB
A data structure to contain both the locations of the primitives on the device and instance assignments to said primitives locations, aka placements.
class PrimitiveDB
A data structure to contain locations of the primitives on the device.
class TclEmitter
Instantiate for all Tcl emissions.
Functions
void registerMSFTPasses ()
InstanceOp getInstance (MSFTModuleOp root, SymbolRefAttr path)
Find the instance in the instance hierarchy as specified by the instance names in 'path'.
LogicalResult verifyDynInstData (Operation *)
std::unique_ptr< Pass > createLowerInstancesPass ()
std::unique_ptr< Pass > createLowerToHWPass ()
std::unique_ptr< Pass > createExportTclPass ()
std::unique_ptr< Pass > createPartitionPass ()
std::unique_ptr< Pass > createWireCleanupPass ()
Function Documentation
createExportTclPass()
std::unique_ptr<Pass> circt::msft::createExportTclPass ()
Definition at line 518 of file MSFTPasses.cpp.
createLowerInstancesPass()
std::unique_ptr<Pass> circt::msft::createLowerInstancesPass ()
Definition at line 232 of file MSFTPasses.cpp.
createLowerToHWPass()
std::unique_ptr<Pass> circt::msft::createLowerToHWPass ()
Definition at line 432 of file MSFTPasses.cpp.
createPartitionPass()
std::unique_ptr<Pass> circt::msft::createPartitionPass ()
Definition at line 1431 of file MSFTPasses.cpp.
createWireCleanupPass()
std::unique_ptr<Pass> circt::msft::createWireCleanupPass ()
Definition at line 1667 of file MSFTPasses.cpp.
getInstance()
msft::InstanceOp circt::msft::getInstance (MSFTModuleOp root, SymbolRefAttr path)
Find the instance in the instance hierarchy as specified by the instance names in 'path'.
Definition at line 76 of file MSFTDialect.cpp.
References getInstance().
Referenced by circtMSFTGetInstance(), and getInstance().
registerMSFTPasses()
void circt::msft::registerMSFTPasses ()
Definition at line 1678 of file MSFTPasses.cpp.
References registerPasses().
Referenced by mlirMSFTRegisterPasses(), and circt::registerAllPasses().
verifyDynInstData()
LogicalResult circt::msft::verifyDynInstData (Operation * op)
Definition at line 15 of file MSFTOpInterfaces.cpp.