CIRCT: lib/Conversion/StandardToHandshake/StandardToHandshake.cpp File Reference
StandardToHandshake.cpp File Reference
#include "circt/Conversion/StandardToHandshake.h"
#include "../PassDetail.h"
#include "circt/Dialect/Handshake/HandshakeOps.h"
#include "circt/Dialect/Handshake/HandshakePasses.h"
#include "circt/Dialect/StaticLogic/StaticLogic.h"
#include "circt/Support/BackedgeBuilder.h"
#include "mlir/Conversion/AffineToStandard/AffineToStandard.h"
#include "mlir/Dialect/Affine/Analysis/AffineAnalysis.h"
#include "mlir/Dialect/Affine/Analysis/AffineStructures.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/Affine/Utils.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Types.h"
#include "mlir/IR/Value.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/raw_ostream.h"
#include <list>
#include <map>
Classes
class LowerFuncOpTarget< TFuncOp >
struct PartialLowerFuncOp< TFuncOp >
Default function for partial lowering of handshake::FuncOp.
class FuncOpLowering
class LoopNetworkRewriter
struct HandshakeCanonicalizePattern
Macros
#define returnOnError(logicalResult)
Typedefs
typedef DenseMap< Block *, std::vector< Value > > BlockValues
typedef DenseMap< Block *, std::vector< Operation * > > BlockOps
typedef DenseMap< Value, Operation * > blockArgPairs
typedef llvm::MapVector< Value, std::vector< Operation * > > MemRefToMemoryAccessOp
using BFSCallback = llvm::function_ref< BFSNextState(Block *)>
Enumerations
enum BFSNextState { BFSNextState::Halt, BFSNextState::SkipSuccessors, BFSNextState::Continue }
Functions
template<typename TConv , typename TFuncOp , typename... TArgs>
LogicalResult lowerToHandshake (TFuncOp op, MLIRContext *context, TArgs &...args)
Calls to rewriter.replaceOpWithNewOp are invalid, given the commitment of all side-effects of of any op replacements are deferred until after the return of matchAndRewrite.
template<typename TFuncOp >
LogicalResult partiallyLowerFuncOp (const std::function< LogicalResult(TFuncOp, ConversionPatternRewriter &)> &loweringFunc, MLIRContext *ctx, TFuncOp funcOp)
void removeBasicBlocks (handshake::FuncOp funcOp)
Remove basic blocks inside the given FuncOp.
BlockValues getBlockUses (handshake::FuncOp f)
BlockValues getBlockDefs (handshake::FuncOp f)
std::vector< Value > vectorUnion (ArrayRef< Value > v1, ArrayRef< Value > v2)
std::vector< Value > vectorDiff (ArrayRef< Value > v1, ArrayRef< Value > v2)
BlockValues livenessAnalysis (handshake::FuncOp f)
unsigned getBlockPredecessorCount (Block *block)
bool blockHasSrcOp (Value val, Block *block)
Value getMergeOperand (Operation *op, Block *predBlock, BlockOps blockMerges)
void removeBlockOperands (handshake::FuncOp f)
template<typename TOp >
Operation * getFirstOp (Block *block)
Returns the first occurance of an operation of type TOp, else, returns null op.
Operation * getControlMerge (Block *block)
ConditionalBranchOp getControlCondBranch (Block *block)
void reconnectMergeOps (handshake::FuncOp f, BlockOps blockMerges, blockArgPairs &mergePairs)
bool isLiveOut (Value val)
int getBranchCount (Value val, Block *block)
static bool hasMultiplePredecessors (Block *block)
static void blockBFS (Block *start, BFSCallback callback)
static bool isReachable (Block *from, Block *to)
static Value getOperandFromBlock (MuxOp mux, Block *block)
static std::vector< Value > getSortedInputs (ControlMergeOp cmerge, MuxOp mux)
Value getSuccResult (Operation *termOp, Operation *newOp, Block *succBlock)
LogicalResult checkUseCount (Operation *op, Value res)
LogicalResult checkSuccessorBlocks (Operation *op, Value res)
LogicalResult checkMergeOps (MergeLikeOpInterface mergeOp, bool disableTaskPipelining)
LogicalResult checkDataflowConversion (handshake::FuncOp f, bool disableTaskPipelining)
Value getBlockControlValue (Block *block)
LogicalResult getOpMemRef (Operation *op, Value &out)
bool isMemoryOp (Operation *op)
std::vector< Block * > getOperationBlocks (ArrayRef< Operation * > ops)
SmallVector< Value, 8 > getResultsToMemory (Operation *op)
void addLazyForks (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
void addMemOpForks (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
void removeAllocOps (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
void removeRedundantSinks (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
void addJoinOps (ConversionPatternRewriter &rewriter, ArrayRef< Value > controlVals)
std::vector< Value > getControlValues (ArrayRef< Operation * > memOps)
void addValueToOperands (Operation *op, Value val)
void setLoadDataInputs (ArrayRef< Operation * > memOps, Operation *memOp)
LogicalResult setJoinControlInputs (ArrayRef< Operation * > memOps, Operation *memOp, int offset, ArrayRef< int > cntrlInd)
static Operation * findStartOp (Region *region)
static LogicalResult lowerFuncOp (func::FuncOp funcOp, MLIRContext *ctx, bool sourceConstants, bool disableTaskPipelining)
Macro Definition Documentation
returnOnError
#define returnOnError (logicalResult)
Value:
  if (failed(logicalResult))                                                   \
    return logicalResult;
Definition at line 156 of file StandardToHandshake.cpp.
Typedef Documentation
BFSCallback
using BFSCallback = llvm::function_ref<BFSNextState(Block *)>
Definition at line 657 of file StandardToHandshake.cpp.
blockArgPairs
typedef DenseMap<Value, Operation *> blockArgPairs
Definition at line 54 of file StandardToHandshake.cpp.
BlockOps
typedef DenseMap<Block *, std::vector<Operation *> > BlockOps
Definition at line 53 of file StandardToHandshake.cpp.
BlockValues
typedef DenseMap<Block *, std::vector<Value> > BlockValues
Definition at line 52 of file StandardToHandshake.cpp.
MemRefToMemoryAccessOp
typedef llvm::MapVector<Value, std::vector<Operation *> > MemRefToMemoryAccessOp
Definition at line 55 of file StandardToHandshake.cpp.
Enumeration Type Documentation
BFSNextState
enum BFSNextState strong
Enumerator
Halt
SkipSuccessors
Continue
Definition at line 656 of file StandardToHandshake.cpp.
Function Documentation
addJoinOps()
void addJoinOps (ConversionPatternRewriter & rewriter, ArrayRef< Value > controlVals)
Definition at line 1511 of file StandardToHandshake.cpp.
Referenced by FuncOpLowering::connectToMemory().
addLazyForks()
void addLazyForks (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 1446 of file StandardToHandshake.cpp.
References getBlockControlValue(), and circt::handshake::insertFork().
Referenced by FuncOpLowering::connectToMemory().
addMemOpForks()
void addMemOpForks (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 1455 of file StandardToHandshake.cpp.
References circt::handshake::insertFork().
Referenced by FuncOpLowering::connectToMemory().
addValueToOperands()
void addValueToOperands (Operation * op, Value val)
Definition at line 1544 of file StandardToHandshake.cpp.
Referenced by setJoinControlInputs(), setLoadDataInputs(), and FuncOpLowering::setMemOpControlInputs().
blockBFS()
static void blockBFS (Block * start, BFSCallback callback) static
Definition at line 659 of file StandardToHandshake.cpp.
References Continue, Halt, and SkipSuccessors.
Referenced by isReachable(), and LoopNetworkRewriter::processOuterLoop().
blockHasSrcOp()
bool blockHasSrcOp (Value val, Block * block)
Definition at line 471 of file StandardToHandshake.cpp.
Referenced by getMergeOperand().
checkDataflowConversion()
LogicalResult checkDataflowConversion (handshake::FuncOp f, bool disableTaskPipelining)
Definition at line 1265 of file StandardToHandshake.cpp.
References checkMergeOps(), checkSuccessorBlocks(), and checkUseCount().
Referenced by lowerFuncOp().
checkMergeOps()
LogicalResult checkMergeOps (MergeLikeOpInterface mergeOp, bool disableTaskPipelining)
Definition at line 1221 of file StandardToHandshake.cpp.
References getBlockPredecessorCount().
Referenced by checkDataflowConversion().
checkSuccessorBlocks()
LogicalResult checkSuccessorBlocks (Operation * op, Value res)
Definition at line 1195 of file StandardToHandshake.cpp.
Referenced by checkDataflowConversion().
checkUseCount()
LogicalResult checkUseCount (Operation * op, Value res)
Definition at line 1180 of file StandardToHandshake.cpp.
Referenced by checkDataflowConversion().
findStartOp()
static Operation* findStartOp (Region * region) static
Definition at line 1747 of file StandardToHandshake.cpp.
Referenced by FuncOpLowering::finalize().
getBlockControlValue()
Value getBlockControlValue (Block * block)
Definition at line 1287 of file StandardToHandshake.cpp.
Referenced by addLazyForks(), getControlValues(), and setJoinControlInputs().
getBlockDefs()
BlockValues getBlockDefs (handshake::FuncOp f)
Definition at line 319 of file StandardToHandshake.cpp.
Referenced by livenessAnalysis().
getBlockPredecessorCount()
unsigned getBlockPredecessorCount (Block * block)
Definition at line 406 of file StandardToHandshake.cpp.
Referenced by checkMergeOps(), FuncOpLowering::insertMerge(), and reconnectMergeOps().
getBlockUses()
BlockValues getBlockUses (handshake::FuncOp f)
Definition at line 288 of file StandardToHandshake.cpp.
Referenced by livenessAnalysis().
getBranchCount()
int getBranchCount (Value val, Block * block)
Definition at line 635 of file StandardToHandshake.cpp.
Referenced by FuncOpLowering::addBranchOps().
getControlCondBranch()
ConditionalBranchOp getControlCondBranch (Block * block)
Definition at line 545 of file StandardToHandshake.cpp.
Referenced by LoopNetworkRewriter::buildExitNetwork().
getControlMerge()
Operation* getControlMerge (Block * block)
Definition at line 541 of file StandardToHandshake.cpp.
Referenced by LoopNetworkRewriter::buildContinueNetwork(), and reconnectMergeOps().
getControlValues()
std::vector<Value> getControlValues (ArrayRef< Operation * > memOps)
Definition at line 1528 of file StandardToHandshake.cpp.
References getBlockControlValue().
Referenced by FuncOpLowering::connectToMemory().
getFirstOp()
template<typename TOp > Operation* getFirstOp (Block * block)
Returns the first occurance of an operation of type TOp, else, returns null op.
Definition at line 534 of file StandardToHandshake.cpp.
getMergeOperand()
Value getMergeOperand (Operation * op, Block * predBlock, BlockOps blockMerges)
Definition at line 482 of file StandardToHandshake.cpp.
References blockHasSrcOp().
Referenced by reconnectMergeOps().
getOperandFromBlock()
static Value getOperandFromBlock (MuxOp mux, Block * block) static
Definition at line 807 of file StandardToHandshake.cpp.
Referenced by getSortedInputs().
getOperationBlocks()
std::vector<Block *> getOperationBlocks (ArrayRef< Operation * > ops)
Definition at line 1415 of file StandardToHandshake.cpp.
getOpMemRef()
LogicalResult getOpMemRef (Operation * op, Value & out)
Definition at line 1302 of file StandardToHandshake.cpp.
Referenced by FuncOpLowering::replaceMemoryOps().
getResultsToMemory()
SmallVector<Value, 8> getResultsToMemory (Operation * op)
Definition at line 1428 of file StandardToHandshake.cpp.
Referenced by FuncOpLowering::connectToMemory().
getSortedInputs()
static std::vector<Value> getSortedInputs (ControlMergeOp cmerge, MuxOp mux) static
Definition at line 820 of file StandardToHandshake.cpp.
References getOperandFromBlock().
getSuccResult()
Value getSuccResult (Operation * termOp, Operation * newOp, Block * succBlock)
Definition at line 1065 of file StandardToHandshake.cpp.
Referenced by FuncOpLowering::addBranchOps().
hasMultiplePredecessors()
static bool hasMultiplePredecessors (Block * block) static
Definition at line 649 of file StandardToHandshake.cpp.
Referenced by LoopNetworkRewriter::processFunction().
isLiveOut()
bool isLiveOut (Value val)
Definition at line 622 of file StandardToHandshake.cpp.
Referenced by FuncOpLowering::addBranchOps().
isMemoryOp()
bool isMemoryOp (Operation * op)
Definition at line 1317 of file StandardToHandshake.cpp.
Referenced by FuncOpLowering::replaceMemoryOps().
isReachable()
static bool isReachable (Block * from, Block * to) static
Definition at line 685 of file StandardToHandshake.cpp.
References blockBFS(), Continue, and Halt.
Referenced by LoopNetworkRewriter::processFunction(), and LoopNetworkRewriter::processOuterLoop().
livenessAnalysis()
BlockValues livenessAnalysis (handshake::FuncOp f)
Definition at line 362 of file StandardToHandshake.cpp.
References getBlockDefs(), getBlockUses(), vectorDiff(), and vectorUnion().
Referenced by FuncOpLowering::addMergeOps().
lowerFuncOp()
static LogicalResult lowerFuncOp (func::FuncOp funcOp, MLIRContext * ctx, bool sourceConstants, bool disableTaskPipelining) static
Definition at line 1831 of file StandardToHandshake.cpp.
References FuncOpLowering::addBranchOps(), circt::handshake::addForkOps(), FuncOpLowering::addMergeOps(), circt::handshake::addSinkOps(), checkDataflowConversion(), FuncOpLowering::connectConstantsToControl(), FuncOpLowering::connectToMemory(), FuncOpLowering::finalize(), FuncOpLowering::loopNetworkRewriting(), FuncOpLowering::replaceCallOps(), FuncOpLowering::replaceMemoryOps(), returnOnError, FuncOpLowering::runPartialLowering(), and FuncOpLowering::setControlOnlyPath().
lowerToHandshake()
template<typename TConv , typename TFuncOp , typename... TArgs> LogicalResult lowerToHandshake (TFuncOp op, MLIRContext * context, TArgs &... args)
Calls to rewriter.replaceOpWithNewOp are invalid, given the commitment of all side-effects of of any op replacements are deferred until after the return of matchAndRewrite.
This is incompatible with the design of the StandardToHandshake pass, which converts a top-level FuncOp in a sequential manner, assuming any side-effects from operand replacements (in particular rewriting of SSA use-def's) are performed instantly. The following convenience function wraps a replacement pattern TConv inside a distinct call to applyPartialConversion, ensuring that any call to rewrite replacement methods have been fully performed after this call. Each replacement pattern is expected to define their own conversion target, to guide pattern matching.
Definition at line 134 of file StandardToHandshake.cpp.
partiallyLowerFuncOp()
template<typename TFuncOp > LogicalResult partiallyLowerFuncOp (const std::function< LogicalResult(TFuncOp, ConversionPatternRewriter &)> & loweringFunc, MLIRContext * ctx, TFuncOp funcOp)
Definition at line 148 of file StandardToHandshake.cpp.
reconnectMergeOps()
void reconnectMergeOps (handshake::FuncOp f, BlockOps blockMerges, blockArgPairs & mergePairs)
Definition at line 553 of file StandardToHandshake.cpp.
References getBlockPredecessorCount(), getControlMerge(), getMergeOperand(), and removeBlockOperands().
Referenced by FuncOpLowering::addMergeOps().
removeAllocOps()
void removeAllocOps (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
TODO(mortbopet): use explicit template parameter when moving to C++20
Definition at line 1470 of file StandardToHandshake.cpp.
Referenced by FuncOpLowering::connectToMemory().
removeBasicBlocks()
void removeBasicBlocks (handshake::FuncOp funcOp)
Remove basic blocks inside the given FuncOp.
This allows the result to be a valid graph region, since multi-basic block regions are not allowed to be graph regions currently.
Definition at line 242 of file StandardToHandshake.cpp.
removeBlockOperands()
void removeBlockOperands (handshake::FuncOp f)
Definition at line 519 of file StandardToHandshake.cpp.
Referenced by reconnectMergeOps().
removeRedundantSinks()
void removeRedundantSinks (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 1490 of file StandardToHandshake.cpp.
Referenced by FuncOpLowering::connectToMemory().
setJoinControlInputs()
LogicalResult setJoinControlInputs (ArrayRef< Operation * > memOps, Operation * memOp, int offset, ArrayRef< int > cntrlInd)
Definition at line 1560 of file StandardToHandshake.cpp.
References addValueToOperands(), and getBlockControlValue().
Referenced by FuncOpLowering::connectToMemory().
setLoadDataInputs()
void setLoadDataInputs (ArrayRef< Operation * > memOps, Operation * memOp)
Definition at line 1551 of file StandardToHandshake.cpp.
References addValueToOperands().
Referenced by FuncOpLowering::connectToMemory().
vectorDiff()
std::vector<Value> vectorDiff (ArrayRef< Value > v1, ArrayRef< Value > v2)
Definition at line 351 of file StandardToHandshake.cpp.
Referenced by livenessAnalysis().
vectorUnion()
std::vector<Value> vectorUnion (ArrayRef< Value > v1, ArrayRef< Value > v2)
Definition at line 339 of file StandardToHandshake.cpp.
Referenced by livenessAnalysis().