CIRCT: Deduper Struct Reference
Deduper Struct Reference
Public Types
using RenameMap = DenseMap< StringAttr, StringAttr >
Public Member Functions
Deduper (InstanceGraph &instanceGraph, SymbolTable &symbolTable, NLAMap &nlaMap, CircuitOp circuit)
void dedup (FModuleLike toModule, FModuleLike fromModule)
Remove the "fromModule", and replace all references to it with the "toModule".
void record (FModuleLike module)
Record the usages of any NLA's in this module, so that we may update the annotation if the parent module is deduped with another module.
Private Types
using LazyValue = std::function< Value(ImplicitLocOpBuilder &)>
This fixes up a partial connect when the field names of a bundle type changes.
Private Member Functions
ModuleNamespace & getNamespace (Operation *module)
Get a cached namespace for a module.
void recordAnnotations (Operation *op)
Record all targets which use an NLA.
template<typename T >
void fixupConnect (ImplicitLocOpBuilder &builder, Value dst, Type dstType, Value src, Type srcType)
This fixes up connects when the field names of a bundle type changes.
template<typename T >
void fixupConnect (T connect, Value newValue, Type oldType)
Replaces a ConnectOp or StrictConnectOp with new bundle types.
void fixupPartialConnect (ImplicitLocOpBuilder &builder, LazyValue dst, Type dstNewType, Type dstOldType, LazyValue src, Type srcNewType, Type srcOldType)
void fixupReferences (Value newValue, Type oldType)
When we replace a bundle type with a similar bundle with different field names, we have to rewrite all the code to use the new field names.
void fixupReferences (FModuleLike toModule, Operation *fromModule)
This is the root method to fixup module references when a module changes.
SmallVector< FlatSymbolRefAttr > createNLAs (StringAttr toModuleName, AnnoTarget to, Operation *fromModule, ArrayRef< Attribute > baseNamepath)
Look up the instantiations of this module and create an NLA for each one, appending the baseNamepath to each NLA.
SmallVector< FlatSymbolRefAttr > createNLAs (FModuleLike toModule, StringAttr toModuleName, AnnoTarget to, FModuleLike fromModule)
Look up the instantiations of this module and create an NLA for each one.
void cloneAnnotation (SmallVector< FlatSymbolRefAttr > &nlas, Annotation anno, ArrayRef< NamedAttribute > attributes, unsigned nonLocalIndex, SmallVector< Annotation > &newAnnotations)
Clone the annotation for each NLA in a list.
void renameModuleInNLA (DenseMap< StringAttr, StringAttr > &renameMap, StringAttr toName, StringAttr fromName, NonLocalAnchor nla)
This finds all NLAs which contain the "from" module, and renames any reference to the "to" module.
void eraseNLA (NonLocalAnchor nla)
This erases the NLA op, all breadcrumb trails, and removes the NLA from every module's NLA map, but it does not delete the NLA reference from the target operation's annotations.
void addAnnotationContext (RenameMap &renameMap, FModuleOp toModule, FModuleOp fromModule)
Process all NLAs referencing the "from" module to point to the "to" module.
void rewriteModuleNLAs (RenameMap &renameMap, FModuleOp toModule, FModuleOp fromModule)
Process all the NLAs that the two modules participate in, replacing references to the "from" module with references to the "to" module, and adding more context if necessary.
void rewriteExtModuleNLAs (RenameMap &renameMap, StringAttr toName, StringAttr fromName)
void makeAnnotationNonLocal (SmallVector< FlatSymbolRefAttr > &nlas, FModuleLike toModule, StringAttr toModuleName, AnnoTarget to, FModuleLike fromModule, AnnoTarget from, Annotation anno, SmallVector< Annotation > &newAnnotations)
Take an annotation, and update it to be a non-local annotation.
void mergeAnnotations (FModuleLike toModule, AnnoTarget to, AnnotationSet toAnnos, FModuleLike fromModule, AnnoTarget from, AnnotationSet fromAnnos)
Merge the annotations of a specific target, either a operation or a port on an operation.
void mergeAnnotations (FModuleLike toModule, Operation *to, FModuleLike fromModule, Operation *from)
Merge all annotations and port annotations on two operations.
void recordSymRenames (RenameMap &renameMap, FModuleLike toModule, Operation *to, FModuleLike fromModule, Operation *from)
void mergeOps (RenameMap &renameMap, FModuleLike toModule, Operation *to, FModuleLike fromModule, Operation *from)
Recursively merge two operations.
void mergeBlocks (RenameMap &renameMap, FModuleLike toModule, Block &toBlock, FModuleLike fromModule, Block &fromBlock)
Recursively merge two blocks.
void mergeRegions (RenameMap &renameMap, FModuleLike toModule, Region &toRegion, FModuleLike fromModule, Region &fromRegion)
Private Attributes
MLIRContext * context
InstanceGraph & instanceGraph
SymbolTable & symbolTable
NLAMap & nlaMap
Block * nlaBlock
We insert all NLAs to the beginning of this block.
DenseMap< Attribute, AnnoTarget > targetMap
StringAttr nonLocalString
StringAttr classString
DenseMap< Operation *, ModuleNamespace > moduleNamespaces
A module namespace cache.
Detailed Description
Definition at line 207 of file Dedup.cpp.
Member Typedef Documentation
LazyValue
using Deduper::LazyValue = std::function<Value(ImplicitLocOpBuilder &)> private
This fixes up a partial connect when the field names of a bundle type changes.
It finds all the fields which were previously connected and replaces them with new partial connects.
Definition at line 335 of file Dedup.cpp.
RenameMap
using Deduper::RenameMap = DenseMap<StringAttr, StringAttr>
Definition at line 209 of file Dedup.cpp.
Constructor & Destructor Documentation
Deduper()
Deduper::Deduper (InstanceGraph & instanceGraph, SymbolTable & symbolTable, NLAMap & nlaMap, CircuitOp circuit) inline
Definition at line 211 of file Dedup.cpp.
Member Function Documentation
addAnnotationContext()
void Deduper::addAnnotationContext (RenameMap & renameMap, FModuleOp toModule, FModuleOp fromModule) inline private
Process all NLAs referencing the "from" module to point to the "to" module.
This is used after merging two modules together.
Definition at line 627 of file Dedup.cpp.
cloneAnnotation()
void Deduper::cloneAnnotation (SmallVector< FlatSymbolRefAttr > & nlas, Annotation anno, ArrayRef< NamedAttribute > attributes, unsigned nonLocalIndex, SmallVector< Annotation > & newAnnotations) inline private
Clone the annotation for each NLA in a list.
Definition at line 553 of file Dedup.cpp.
createNLAs() [1/2]
SmallVector<FlatSymbolRefAttr> Deduper::createNLAs (FModuleLike toModule, StringAttr toModuleName, AnnoTarget to, FModuleLike fromModule) inline private
Look up the instantiations of this module and create an NLA for each one.
This returns an array of symbol references which can be used to reference the NLAs.
Definition at line 544 of file Dedup.cpp.
createNLAs() [2/2]
SmallVector<FlatSymbolRefAttr> Deduper::createNLAs (StringAttr toModuleName, AnnoTarget to, Operation * fromModule, ArrayRef< Attribute > baseNamepath) inline private
Look up the instantiations of this module and create an NLA for each one, appending the baseNamepath to each NLA.
This is used to add more context to an already existing NLA.
Definition at line 482 of file Dedup.cpp.
References circt::calyx::direction::get().
dedup()
void Deduper::dedup (FModuleLike toModule, FModuleLike fromModule) inline
Remove the "fromModule", and replace all references to it with the "toModule".
Modules should be deduplicated in a bottom-up order. Any module which is not deduplicated needs to be recorded with the record call.
Definition at line 222 of file Dedup.cpp.
eraseNLA()
void Deduper::eraseNLA (NonLocalAnchor nla) inline private
This erases the NLA op, all breadcrumb trails, and removes the NLA from every module's NLA map, but it does not delete the NLA reference from the target operation's annotations.
Definition at line 595 of file Dedup.cpp.
References circt::calyx::direction::get().
fixupConnect() [1/2]
template<typename T > void Deduper::fixupConnect (ImplicitLocOpBuilder & builder, Value dst, Type dstType, Value src, Type srcType) inline private
This fixes up connects when the field names of a bundle type changes.
It finds all fields which were previously bulk connected and legalizes it into a connect for each field.
Definition at line 292 of file Dedup.cpp.
fixupConnect() [2/2]
template<typename T > void Deduper::fixupConnect (T connect, Value newValue, Type oldType) inline private
Replaces a ConnectOp or StrictConnectOp with new bundle types.
Definition at line 319 of file Dedup.cpp.
References circt.support::connect().
fixupPartialConnect()
void Deduper::fixupPartialConnect (ImplicitLocOpBuilder & builder, LazyValue dst, Type dstNewType, Type dstOldType, LazyValue src, Type srcNewType, Type srcOldType) inline private
Definition at line 337 of file Dedup.cpp.
fixupReferences() [1/2]
void Deduper::fixupReferences (FModuleLike toModule, Operation * fromModule) inline private
This is the root method to fixup module references when a module changes.
It matches all the results of "to" module with the results of the "from" module.
Definition at line 450 of file Dedup.cpp.
fixupReferences() [2/2]
void Deduper::fixupReferences (Value newValue, Type oldType) inline private
When we replace a bundle type with a similar bundle with different field names, we have to rewrite all the code to use the new field names.
This mostly affects subfield result types and any bulk connects.
Definition at line 397 of file Dedup.cpp.
References circt.support::connect().
getNamespace()
ModuleNamespace& Deduper::getNamespace (Operation * module) inline private
Get a cached namespace for a module.
Definition at line 259 of file Dedup.cpp.
makeAnnotationNonLocal()
void Deduper::makeAnnotationNonLocal (SmallVector< FlatSymbolRefAttr > & nlas, FModuleLike toModule, StringAttr toModuleName, AnnoTarget to, FModuleLike fromModule, AnnoTarget from, Annotation anno, SmallVector< Annotation > & newAnnotations) inline private
Take an annotation, and update it to be a non-local annotation.
If the annotation is already non-local and has enough context, it will be skipped for now.
Definition at line 692 of file Dedup.cpp.
References getAttr().
mergeAnnotations() [1/2]
void Deduper::mergeAnnotations (FModuleLike toModule, AnnoTarget to, AnnotationSet toAnnos, FModuleLike fromModule, AnnoTarget from, AnnotationSet fromAnnos) inline private
Merge the annotations of a specific target, either a operation or a port on an operation.
Definition at line 740 of file Dedup.cpp.
mergeAnnotations() [2/2]
void Deduper::mergeAnnotations (FModuleLike toModule, Operation * to, FModuleLike fromModule, Operation * from) inline private
Merge all annotations and port annotations on two operations.
Definition at line 802 of file Dedup.cpp.
References circt::firrtl::AnnotationSet::forPort().
mergeBlocks()
void Deduper::mergeBlocks (RenameMap & renameMap, FModuleLike toModule, Block & toBlock, FModuleLike fromModule, Block & fromBlock) inline private
Recursively merge two blocks.
Definition at line 906 of file Dedup.cpp.
mergeOps()
void Deduper::mergeOps (RenameMap & renameMap, FModuleLike toModule, Operation * to, FModuleLike fromModule, Operation * from) inline private
Recursively merge two operations.
Definition at line 887 of file Dedup.cpp.
References circt::calyx::direction::get(), and mergeRegions().
mergeRegions()
void Deduper::mergeRegions (RenameMap & renameMap, FModuleLike toModule, Region & toRegion, FModuleLike fromModule, Region & fromRegion) inline private
Definition at line 914 of file Dedup.cpp.
record()
void Deduper::record (FModuleLike module) inline
Record the usages of any NLA's in this module, so that we may update the annotation if the parent module is deduped with another module.
Definition at line 245 of file Dedup.cpp.
recordAnnotations()
void Deduper::recordAnnotations (Operation * op) inline private
Record all targets which use an NLA.
Definition at line 265 of file Dedup.cpp.
recordSymRenames()
void Deduper::recordSymRenames (RenameMap & renameMap, FModuleLike toModule, Operation * to, FModuleLike fromModule, Operation * from) inline private
Definition at line 830 of file Dedup.cpp.
References circt::calyx::direction::get().
renameModuleInNLA()
void Deduper::renameModuleInNLA (DenseMap< StringAttr, StringAttr > & renameMap, StringAttr toName, StringAttr fromName, NonLocalAnchor nla) inline private
This finds all NLAs which contain the "from" module, and renames any reference to the "to" module.
Definition at line 570 of file Dedup.cpp.
References circt::calyx::direction::get().
rewriteExtModuleNLAs()
void Deduper::rewriteExtModuleNLAs (RenameMap & renameMap, StringAttr toName, StringAttr fromName) inline private
Definition at line 683 of file Dedup.cpp.
rewriteModuleNLAs()
void Deduper::rewriteModuleNLAs (RenameMap & renameMap, FModuleOp toModule, FModuleOp fromModule) inline private
Process all the NLAs that the two modules participate in, replacing references to the "from" module with references to the "to" module, and adding more context if necessary.
Definition at line 675 of file Dedup.cpp.
Member Data Documentation
classString
StringAttr Deduper::classString private
Definition at line 940 of file Dedup.cpp.
context
MLIRContext* Deduper::context private
Definition at line 922 of file Dedup.cpp.
instanceGraph
InstanceGraph& Deduper::instanceGraph private
Definition at line 923 of file Dedup.cpp.
moduleNamespaces
DenseMap<Operation *, ModuleNamespace> Deduper::moduleNamespaces private
A module namespace cache.
Definition at line 943 of file Dedup.cpp.
nlaBlock
Block* Deduper::nlaBlock private
We insert all NLAs to the beginning of this block.
Definition at line 931 of file Dedup.cpp.
nlaMap
NLAMap& Deduper::nlaMap private
Definition at line 928 of file Dedup.cpp.
nonLocalString
StringAttr Deduper::nonLocalString private
Definition at line 939 of file Dedup.cpp.
symbolTable
SymbolTable& Deduper::symbolTable private
Definition at line 924 of file Dedup.cpp.
targetMap
DenseMap<Attribute, AnnoTarget> Deduper::targetMap private
Definition at line 936 of file Dedup.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/FIRRTL/Transforms/Dedup.cpp