CIRCT: circt::WhileOpInterface Struct Reference
circt::WhileOpInterface Struct Reference
A structure that abstracts a WhileOp or PipelineWhileOp to provide a consistent interface.
Public Member Functions
WhileOpInterface (Operation *op)
Block::BlockArgListType getBodyArgs ()
Block * getBodyBlock ()
Block * getConditionBlock ()
Value getConditionValue ()
bool isPipelined ()
Optional< uint64_t > getBound ()
Operation * getOperation ()
Static Public Member Functions
static bool isSupported (Operation *op)
Private Attributes
Operation * impl
Detailed Description
A structure that abstracts a WhileOp or PipelineWhileOp to provide a consistent interface.
Definition at line 49 of file SCFToCalyx.cpp.
Constructor & Destructor Documentation
WhileOpInterface()
circt::WhileOpInterface::WhileOpInterface (Operation * op) inline
Definition at line 50 of file SCFToCalyx.cpp.
References isSupported().
Member Function Documentation
getBodyArgs()
Block::BlockArgListType circt::WhileOpInterface::getBodyArgs () inline
Definition at line 62 of file SCFToCalyx.cpp.
Referenced by circt::ComponentLoweringState::addWhileIterReg(), and circt::BuildWhileGroups::PartiallyLowerFuncToComp().
getBodyBlock()
Block* circt::WhileOpInterface::getBodyBlock () inline
Definition at line 71 of file SCFToCalyx.cpp.
getBound()
Optional<uint64_t> circt::WhileOpInterface::getBound () inline
Definition at line 96 of file SCFToCalyx.cpp.
References None.
Referenced by circt::BuildControl::buildWhileCtrlOp().
getConditionBlock()
Block* circt::WhileOpInterface::getConditionBlock () inline
Definition at line 79 of file SCFToCalyx.cpp.
Referenced by circt::BuildWhileGroups::PartiallyLowerFuncToComp().
getConditionValue()
Value circt::WhileOpInterface::getConditionValue () inline
Definition at line 86 of file SCFToCalyx.cpp.
Referenced by circt::BuildControl::buildWhileCtrlOp().
getOperation()
Operation* circt::WhileOpInterface::getOperation () inline
Definition at line 102 of file SCFToCalyx.cpp.
Referenced by circt::ComponentLoweringState::addWhileIterReg(), circt::BuildControl::buildWhileCtrlOp(), circt::buildWhileIterArgAssignments(), circt::ComponentLoweringState::getWhileIterRegs(), circt::ComponentLoweringState::getWhileLatchGroup(), circt::BuildWhileGroups::PartiallyLowerFuncToComp(), circt::LateSSAReplacement::PartiallyLowerFuncToComp(), and circt::ComponentLoweringState::setWhileLatchGroup().
isPipelined()
bool circt::WhileOpInterface::isPipelined () inline
Definition at line 94 of file SCFToCalyx.cpp.
Referenced by circt::BuildWhileGroups::PartiallyLowerFuncToComp().
isSupported()
static bool circt::WhileOpInterface::isSupported (Operation * op) inline static
Definition at line 58 of file SCFToCalyx.cpp.
Member Data Documentation
impl
Operation* circt::WhileOpInterface::impl private
Definition at line 105 of file SCFToCalyx.cpp.
The documentation for this struct was generated from the following file:
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp